/*
微信公众号订阅消息相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package subscribe_message

import (
	"bytes"
	"context"
	"io/ioutil"
	"net/http"
	"net/url"
)

// SubscribemessageApiService SubscribemessageApi service
type SubscribemessageApiService service

type ApiMessageSubscribeSendPostRequest struct {
	ctx                         context.Context
	ApiService                  *SubscribemessageApiService
	accessToken                 *string
	subscribeMessageSendRequest *SubscribeMessageSendRequest
}

// access_token
func (r ApiMessageSubscribeSendPostRequest) AccessToken(accessToken string) ApiMessageSubscribeSendPostRequest {
	r.accessToken = &accessToken
	return r
}

func (r ApiMessageSubscribeSendPostRequest) SubscribeMessageSendRequest(subscribeMessageSendRequest SubscribeMessageSendRequest) ApiMessageSubscribeSendPostRequest {
	r.subscribeMessageSendRequest = &subscribeMessageSendRequest
	return r
}

func (r ApiMessageSubscribeSendPostRequest) Execute() (*SubscribeMessageSendResponse, *http.Response, error) {
	return r.ApiService.MessageSubscribeSendPostExecute(r)
}

/*
MessageSubscribeSendPost 发送订阅消息

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiMessageSubscribeSendPostRequest
*/
func (a *SubscribemessageApiService) MessageSubscribeSendPost(ctx context.Context) ApiMessageSubscribeSendPostRequest {
	return ApiMessageSubscribeSendPostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return SubscribeMessageSendResponse
func (a *SubscribemessageApiService) MessageSubscribeSendPostExecute(r ApiMessageSubscribeSendPostRequest) (*SubscribeMessageSendResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *SubscribeMessageSendResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SubscribemessageApiService.MessageSubscribeSendPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/message/subscribe/send"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.accessToken == nil {
		return localVarReturnValue, nil, reportError("accessToken is required and must be specified")
	}
	if r.subscribeMessageSendRequest == nil {
		return localVarReturnValue, nil, reportError("subscribeMessageSendRequest is required and must be specified")
	}

	parameterAddToQuery(localVarQueryParams, "access_token", r.accessToken, "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.subscribeMessageSendRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
