/*
微信公众号订阅消息相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package subscribe_message

import (
	"encoding/json"
)

// checks if the SubscribeMessageSendResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscribeMessageSendResponse{}

// SubscribeMessageSendResponse struct for SubscribeMessageSendResponse
type SubscribeMessageSendResponse struct {
	// 返回码
	Errcode *int32 `json:"errcode,omitempty"`
	// 对返回码的文本描述内容
	Errmsg *string `json:"errmsg,omitempty"`
}

// NewSubscribeMessageSendResponse instantiates a new SubscribeMessageSendResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscribeMessageSendResponse() *SubscribeMessageSendResponse {
	this := SubscribeMessageSendResponse{}
	return &this
}

// NewSubscribeMessageSendResponseWithDefaults instantiates a new SubscribeMessageSendResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscribeMessageSendResponseWithDefaults() *SubscribeMessageSendResponse {
	this := SubscribeMessageSendResponse{}
	return &this
}

// GetErrcode returns the Errcode field value if set, zero value otherwise.
func (o *SubscribeMessageSendResponse) GetErrcode() int32 {
	if o == nil || isNil(o.Errcode) {
		var ret int32
		return ret
	}
	return *o.Errcode
}

// GetErrcodeOk returns a tuple with the Errcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscribeMessageSendResponse) GetErrcodeOk() (*int32, bool) {
	if o == nil || isNil(o.Errcode) {
		return nil, false
	}
	return o.Errcode, true
}

// HasErrcode returns a boolean if a field has been set.
func (o *SubscribeMessageSendResponse) HasErrcode() bool {
	if o != nil && !isNil(o.Errcode) {
		return true
	}

	return false
}

// SetErrcode gets a reference to the given int32 and assigns it to the Errcode field.
func (o *SubscribeMessageSendResponse) SetErrcode(v int32) {
	o.Errcode = &v
}

// GetErrmsg returns the Errmsg field value if set, zero value otherwise.
func (o *SubscribeMessageSendResponse) GetErrmsg() string {
	if o == nil || isNil(o.Errmsg) {
		var ret string
		return ret
	}
	return *o.Errmsg
}

// GetErrmsgOk returns a tuple with the Errmsg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscribeMessageSendResponse) GetErrmsgOk() (*string, bool) {
	if o == nil || isNil(o.Errmsg) {
		return nil, false
	}
	return o.Errmsg, true
}

// HasErrmsg returns a boolean if a field has been set.
func (o *SubscribeMessageSendResponse) HasErrmsg() bool {
	if o != nil && !isNil(o.Errmsg) {
		return true
	}

	return false
}

// SetErrmsg gets a reference to the given string and assigns it to the Errmsg field.
func (o *SubscribeMessageSendResponse) SetErrmsg(v string) {
	o.Errmsg = &v
}

func (o SubscribeMessageSendResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscribeMessageSendResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Errcode) {
		toSerialize["errcode"] = o.Errcode
	}
	if !isNil(o.Errmsg) {
		toSerialize["errmsg"] = o.Errmsg
	}
	return toSerialize, nil
}

type NullableSubscribeMessageSendResponse struct {
	value *SubscribeMessageSendResponse
	isSet bool
}

func (v NullableSubscribeMessageSendResponse) Get() *SubscribeMessageSendResponse {
	return v.value
}

func (v *NullableSubscribeMessageSendResponse) Set(val *SubscribeMessageSendResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscribeMessageSendResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscribeMessageSendResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscribeMessageSendResponse(val *SubscribeMessageSendResponse) *NullableSubscribeMessageSendResponse {
	return &NullableSubscribeMessageSendResponse{value: val, isSet: true}
}

func (v NullableSubscribeMessageSendResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscribeMessageSendResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
