/*
微信公众号素材相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package material

import (
	"encoding/json"
)

// checks if the BatchgetMaterialResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchgetMaterialResponse{}

// BatchgetMaterialResponse struct for BatchgetMaterialResponse
type BatchgetMaterialResponse struct {
	// 返回码
	Errcode *int32 `json:"errcode,omitempty"`
	// 对返回码的文本描述内容
	Errmsg *string `json:"errmsg,omitempty"`
	// 该类型的素材的总数
	TotalCount *int32 `json:"total_count,omitempty"`
	// 本次调用获取的素材的数量
	ItemCount *int32                              `json:"item_count,omitempty"`
	Item      []BatchgetMaterialResponseItemInner `json:"item,omitempty"`
}

// NewBatchgetMaterialResponse instantiates a new BatchgetMaterialResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchgetMaterialResponse() *BatchgetMaterialResponse {
	this := BatchgetMaterialResponse{}
	return &this
}

// NewBatchgetMaterialResponseWithDefaults instantiates a new BatchgetMaterialResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchgetMaterialResponseWithDefaults() *BatchgetMaterialResponse {
	this := BatchgetMaterialResponse{}
	return &this
}

// GetErrcode returns the Errcode field value if set, zero value otherwise.
func (o *BatchgetMaterialResponse) GetErrcode() int32 {
	if o == nil || isNil(o.Errcode) {
		var ret int32
		return ret
	}
	return *o.Errcode
}

// GetErrcodeOk returns a tuple with the Errcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchgetMaterialResponse) GetErrcodeOk() (*int32, bool) {
	if o == nil || isNil(o.Errcode) {
		return nil, false
	}
	return o.Errcode, true
}

// HasErrcode returns a boolean if a field has been set.
func (o *BatchgetMaterialResponse) HasErrcode() bool {
	if o != nil && !isNil(o.Errcode) {
		return true
	}

	return false
}

// SetErrcode gets a reference to the given int32 and assigns it to the Errcode field.
func (o *BatchgetMaterialResponse) SetErrcode(v int32) {
	o.Errcode = &v
}

// GetErrmsg returns the Errmsg field value if set, zero value otherwise.
func (o *BatchgetMaterialResponse) GetErrmsg() string {
	if o == nil || isNil(o.Errmsg) {
		var ret string
		return ret
	}
	return *o.Errmsg
}

// GetErrmsgOk returns a tuple with the Errmsg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchgetMaterialResponse) GetErrmsgOk() (*string, bool) {
	if o == nil || isNil(o.Errmsg) {
		return nil, false
	}
	return o.Errmsg, true
}

// HasErrmsg returns a boolean if a field has been set.
func (o *BatchgetMaterialResponse) HasErrmsg() bool {
	if o != nil && !isNil(o.Errmsg) {
		return true
	}

	return false
}

// SetErrmsg gets a reference to the given string and assigns it to the Errmsg field.
func (o *BatchgetMaterialResponse) SetErrmsg(v string) {
	o.Errmsg = &v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *BatchgetMaterialResponse) GetTotalCount() int32 {
	if o == nil || isNil(o.TotalCount) {
		var ret int32
		return ret
	}
	return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchgetMaterialResponse) GetTotalCountOk() (*int32, bool) {
	if o == nil || isNil(o.TotalCount) {
		return nil, false
	}
	return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *BatchgetMaterialResponse) HasTotalCount() bool {
	if o != nil && !isNil(o.TotalCount) {
		return true
	}

	return false
}

// SetTotalCount gets a reference to the given int32 and assigns it to the TotalCount field.
func (o *BatchgetMaterialResponse) SetTotalCount(v int32) {
	o.TotalCount = &v
}

// GetItemCount returns the ItemCount field value if set, zero value otherwise.
func (o *BatchgetMaterialResponse) GetItemCount() int32 {
	if o == nil || isNil(o.ItemCount) {
		var ret int32
		return ret
	}
	return *o.ItemCount
}

// GetItemCountOk returns a tuple with the ItemCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchgetMaterialResponse) GetItemCountOk() (*int32, bool) {
	if o == nil || isNil(o.ItemCount) {
		return nil, false
	}
	return o.ItemCount, true
}

// HasItemCount returns a boolean if a field has been set.
func (o *BatchgetMaterialResponse) HasItemCount() bool {
	if o != nil && !isNil(o.ItemCount) {
		return true
	}

	return false
}

// SetItemCount gets a reference to the given int32 and assigns it to the ItemCount field.
func (o *BatchgetMaterialResponse) SetItemCount(v int32) {
	o.ItemCount = &v
}

// GetItem returns the Item field value if set, zero value otherwise.
func (o *BatchgetMaterialResponse) GetItem() []BatchgetMaterialResponseItemInner {
	if o == nil || isNil(o.Item) {
		var ret []BatchgetMaterialResponseItemInner
		return ret
	}
	return o.Item
}

// GetItemOk returns a tuple with the Item field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchgetMaterialResponse) GetItemOk() ([]BatchgetMaterialResponseItemInner, bool) {
	if o == nil || isNil(o.Item) {
		return nil, false
	}
	return o.Item, true
}

// HasItem returns a boolean if a field has been set.
func (o *BatchgetMaterialResponse) HasItem() bool {
	if o != nil && !isNil(o.Item) {
		return true
	}

	return false
}

// SetItem gets a reference to the given []BatchgetMaterialResponseItemInner and assigns it to the Item field.
func (o *BatchgetMaterialResponse) SetItem(v []BatchgetMaterialResponseItemInner) {
	o.Item = v
}

func (o BatchgetMaterialResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchgetMaterialResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Errcode) {
		toSerialize["errcode"] = o.Errcode
	}
	if !isNil(o.Errmsg) {
		toSerialize["errmsg"] = o.Errmsg
	}
	if !isNil(o.TotalCount) {
		toSerialize["total_count"] = o.TotalCount
	}
	if !isNil(o.ItemCount) {
		toSerialize["item_count"] = o.ItemCount
	}
	if !isNil(o.Item) {
		toSerialize["item"] = o.Item
	}
	return toSerialize, nil
}

type NullableBatchgetMaterialResponse struct {
	value *BatchgetMaterialResponse
	isSet bool
}

func (v NullableBatchgetMaterialResponse) Get() *BatchgetMaterialResponse {
	return v.value
}

func (v *NullableBatchgetMaterialResponse) Set(val *BatchgetMaterialResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchgetMaterialResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchgetMaterialResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchgetMaterialResponse(val *BatchgetMaterialResponse) *NullableBatchgetMaterialResponse {
	return &NullableBatchgetMaterialResponse{value: val, isSet: true}
}

func (v NullableBatchgetMaterialResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchgetMaterialResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
