/*
微信公众号素材相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package material

import (
	"encoding/json"
)

// checks if the BatchgetMaterialResponseItemInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchgetMaterialResponseItemInner{}

// BatchgetMaterialResponseItemInner struct for BatchgetMaterialResponseItemInner
type BatchgetMaterialResponseItemInner struct {
	MediaId *string                                   `json:"media_id,omitempty"`
	Content *BatchgetMaterialResponseItemInnerContent `json:"content,omitempty"`
	// 图文页的URL，或者，当获取的列表是图片素材列表时，该字段是图片的URL
	Url *string `json:"url,omitempty"`
	// 这篇图文消息素材的最后更新时间
	UpdateTime *int64 `json:"update_time,omitempty"`
	// 文件名称
	Name *string `json:"name,omitempty"`
}

// NewBatchgetMaterialResponseItemInner instantiates a new BatchgetMaterialResponseItemInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchgetMaterialResponseItemInner() *BatchgetMaterialResponseItemInner {
	this := BatchgetMaterialResponseItemInner{}
	return &this
}

// NewBatchgetMaterialResponseItemInnerWithDefaults instantiates a new BatchgetMaterialResponseItemInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchgetMaterialResponseItemInnerWithDefaults() *BatchgetMaterialResponseItemInner {
	this := BatchgetMaterialResponseItemInner{}
	return &this
}

// GetMediaId returns the MediaId field value if set, zero value otherwise.
func (o *BatchgetMaterialResponseItemInner) GetMediaId() string {
	if o == nil || isNil(o.MediaId) {
		var ret string
		return ret
	}
	return *o.MediaId
}

// GetMediaIdOk returns a tuple with the MediaId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchgetMaterialResponseItemInner) GetMediaIdOk() (*string, bool) {
	if o == nil || isNil(o.MediaId) {
		return nil, false
	}
	return o.MediaId, true
}

// HasMediaId returns a boolean if a field has been set.
func (o *BatchgetMaterialResponseItemInner) HasMediaId() bool {
	if o != nil && !isNil(o.MediaId) {
		return true
	}

	return false
}

// SetMediaId gets a reference to the given string and assigns it to the MediaId field.
func (o *BatchgetMaterialResponseItemInner) SetMediaId(v string) {
	o.MediaId = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *BatchgetMaterialResponseItemInner) GetContent() BatchgetMaterialResponseItemInnerContent {
	if o == nil || isNil(o.Content) {
		var ret BatchgetMaterialResponseItemInnerContent
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchgetMaterialResponseItemInner) GetContentOk() (*BatchgetMaterialResponseItemInnerContent, bool) {
	if o == nil || isNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *BatchgetMaterialResponseItemInner) HasContent() bool {
	if o != nil && !isNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given BatchgetMaterialResponseItemInnerContent and assigns it to the Content field.
func (o *BatchgetMaterialResponseItemInner) SetContent(v BatchgetMaterialResponseItemInnerContent) {
	o.Content = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *BatchgetMaterialResponseItemInner) GetUrl() string {
	if o == nil || isNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchgetMaterialResponseItemInner) GetUrlOk() (*string, bool) {
	if o == nil || isNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *BatchgetMaterialResponseItemInner) HasUrl() bool {
	if o != nil && !isNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *BatchgetMaterialResponseItemInner) SetUrl(v string) {
	o.Url = &v
}

// GetUpdateTime returns the UpdateTime field value if set, zero value otherwise.
func (o *BatchgetMaterialResponseItemInner) GetUpdateTime() int64 {
	if o == nil || isNil(o.UpdateTime) {
		var ret int64
		return ret
	}
	return *o.UpdateTime
}

// GetUpdateTimeOk returns a tuple with the UpdateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchgetMaterialResponseItemInner) GetUpdateTimeOk() (*int64, bool) {
	if o == nil || isNil(o.UpdateTime) {
		return nil, false
	}
	return o.UpdateTime, true
}

// HasUpdateTime returns a boolean if a field has been set.
func (o *BatchgetMaterialResponseItemInner) HasUpdateTime() bool {
	if o != nil && !isNil(o.UpdateTime) {
		return true
	}

	return false
}

// SetUpdateTime gets a reference to the given int64 and assigns it to the UpdateTime field.
func (o *BatchgetMaterialResponseItemInner) SetUpdateTime(v int64) {
	o.UpdateTime = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *BatchgetMaterialResponseItemInner) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchgetMaterialResponseItemInner) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *BatchgetMaterialResponseItemInner) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *BatchgetMaterialResponseItemInner) SetName(v string) {
	o.Name = &v
}

func (o BatchgetMaterialResponseItemInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchgetMaterialResponseItemInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.MediaId) {
		toSerialize["media_id"] = o.MediaId
	}
	if !isNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !isNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !isNil(o.UpdateTime) {
		toSerialize["update_time"] = o.UpdateTime
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableBatchgetMaterialResponseItemInner struct {
	value *BatchgetMaterialResponseItemInner
	isSet bool
}

func (v NullableBatchgetMaterialResponseItemInner) Get() *BatchgetMaterialResponseItemInner {
	return v.value
}

func (v *NullableBatchgetMaterialResponseItemInner) Set(val *BatchgetMaterialResponseItemInner) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchgetMaterialResponseItemInner) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchgetMaterialResponseItemInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchgetMaterialResponseItemInner(val *BatchgetMaterialResponseItemInner) *NullableBatchgetMaterialResponseItemInner {
	return &NullableBatchgetMaterialResponseItemInner{value: val, isSet: true}
}

func (v NullableBatchgetMaterialResponseItemInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchgetMaterialResponseItemInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
