/*
微信公众号素材相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package material

import (
	"encoding/json"
)

// checks if the GetMaterialRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMaterialRequest{}

// GetMaterialRequest struct for GetMaterialRequest
type GetMaterialRequest struct {
	// 要获取的素材的media_id
	MediaId *string `json:"media_id,omitempty"`
}

// NewGetMaterialRequest instantiates a new GetMaterialRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMaterialRequest() *GetMaterialRequest {
	this := GetMaterialRequest{}
	return &this
}

// NewGetMaterialRequestWithDefaults instantiates a new GetMaterialRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMaterialRequestWithDefaults() *GetMaterialRequest {
	this := GetMaterialRequest{}
	return &this
}

// GetMediaId returns the MediaId field value if set, zero value otherwise.
func (o *GetMaterialRequest) GetMediaId() string {
	if o == nil || isNil(o.MediaId) {
		var ret string
		return ret
	}
	return *o.MediaId
}

// GetMediaIdOk returns a tuple with the MediaId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMaterialRequest) GetMediaIdOk() (*string, bool) {
	if o == nil || isNil(o.MediaId) {
		return nil, false
	}
	return o.MediaId, true
}

// HasMediaId returns a boolean if a field has been set.
func (o *GetMaterialRequest) HasMediaId() bool {
	if o != nil && !isNil(o.MediaId) {
		return true
	}

	return false
}

// SetMediaId gets a reference to the given string and assigns it to the MediaId field.
func (o *GetMaterialRequest) SetMediaId(v string) {
	o.MediaId = &v
}

func (o GetMaterialRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMaterialRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.MediaId) {
		toSerialize["media_id"] = o.MediaId
	}
	return toSerialize, nil
}

type NullableGetMaterialRequest struct {
	value *GetMaterialRequest
	isSet bool
}

func (v NullableGetMaterialRequest) Get() *GetMaterialRequest {
	return v.value
}

func (v *NullableGetMaterialRequest) Set(val *GetMaterialRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMaterialRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMaterialRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMaterialRequest(val *GetMaterialRequest) *NullableGetMaterialRequest {
	return &NullableGetMaterialRequest{value: val, isSet: true}
}

func (v NullableGetMaterialRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMaterialRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
