/*
微信公众号素材相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package material

import (
	"encoding/json"
)

// checks if the BatchgetMaterialResponseItemInnerContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchgetMaterialResponseItemInnerContent{}

// BatchgetMaterialResponseItemInnerContent struct for BatchgetMaterialResponseItemInnerContent
type BatchgetMaterialResponseItemInnerContent struct {
	NewsItem []BatchgetMaterialResponseItemInnerContentNewsItemInner `json:"news_item,omitempty"`
}

// NewBatchgetMaterialResponseItemInnerContent instantiates a new BatchgetMaterialResponseItemInnerContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchgetMaterialResponseItemInnerContent() *BatchgetMaterialResponseItemInnerContent {
	this := BatchgetMaterialResponseItemInnerContent{}
	return &this
}

// NewBatchgetMaterialResponseItemInnerContentWithDefaults instantiates a new BatchgetMaterialResponseItemInnerContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchgetMaterialResponseItemInnerContentWithDefaults() *BatchgetMaterialResponseItemInnerContent {
	this := BatchgetMaterialResponseItemInnerContent{}
	return &this
}

// GetNewsItem returns the NewsItem field value if set, zero value otherwise.
func (o *BatchgetMaterialResponseItemInnerContent) GetNewsItem() []BatchgetMaterialResponseItemInnerContentNewsItemInner {
	if o == nil || isNil(o.NewsItem) {
		var ret []BatchgetMaterialResponseItemInnerContentNewsItemInner
		return ret
	}
	return o.NewsItem
}

// GetNewsItemOk returns a tuple with the NewsItem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchgetMaterialResponseItemInnerContent) GetNewsItemOk() ([]BatchgetMaterialResponseItemInnerContentNewsItemInner, bool) {
	if o == nil || isNil(o.NewsItem) {
		return nil, false
	}
	return o.NewsItem, true
}

// HasNewsItem returns a boolean if a field has been set.
func (o *BatchgetMaterialResponseItemInnerContent) HasNewsItem() bool {
	if o != nil && !isNil(o.NewsItem) {
		return true
	}

	return false
}

// SetNewsItem gets a reference to the given []BatchgetMaterialResponseItemInnerContentNewsItemInner and assigns it to the NewsItem field.
func (o *BatchgetMaterialResponseItemInnerContent) SetNewsItem(v []BatchgetMaterialResponseItemInnerContentNewsItemInner) {
	o.NewsItem = v
}

func (o BatchgetMaterialResponseItemInnerContent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchgetMaterialResponseItemInnerContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.NewsItem) {
		toSerialize["news_item"] = o.NewsItem
	}
	return toSerialize, nil
}

type NullableBatchgetMaterialResponseItemInnerContent struct {
	value *BatchgetMaterialResponseItemInnerContent
	isSet bool
}

func (v NullableBatchgetMaterialResponseItemInnerContent) Get() *BatchgetMaterialResponseItemInnerContent {
	return v.value
}

func (v *NullableBatchgetMaterialResponseItemInnerContent) Set(val *BatchgetMaterialResponseItemInnerContent) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchgetMaterialResponseItemInnerContent) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchgetMaterialResponseItemInnerContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchgetMaterialResponseItemInnerContent(val *BatchgetMaterialResponseItemInnerContent) *NullableBatchgetMaterialResponseItemInnerContent {
	return &NullableBatchgetMaterialResponseItemInnerContent{value: val, isSet: true}
}

func (v NullableBatchgetMaterialResponseItemInnerContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchgetMaterialResponseItemInnerContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
