/*
微信小程序相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package miniprogram

import (
	"encoding/json"
)

// checks if the GetwxacodeunlimitReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetwxacodeunlimitReq{}

// GetwxacodeunlimitReq struct for GetwxacodeunlimitReq
type GetwxacodeunlimitReq struct {
	// 是 最大32个可见字符，只支持数字，大小写英文以及部分特殊字符：!#$&'()*+,/:;=?@-._~，其它字符请自行编码为合法字符（因不支持%，中文无法使用 urlencode 处理，请使用其他编码方式）
	Scene *string `json:"scene,omitempty"`
	// 主页 否 页面 page，例如 pages/index/index，根路径前不要填加 /，不能携带参数（参数请放在scene字段里），如果不填写这个字段，默认跳主页面
	Page *string `json:"page,omitempty"`
	// true 否 检查page 是否存在，为 true 时 page 必须是已经发布的小程序存在的页面（否则报错）；为 false 时允许小程序未发布或者 page 不存在， 但page 有数量上限（60000个）请勿滥用
	CheckPath *bool `json:"check_path,omitempty"`
	// release\" 否 要打开的小程序版本。正式版为 \"release\"，体验版为 \"trial\"，开发版为 \"develop\"
	EnvVersion *string `json:"env_version,omitempty"`
	// 430 否 二维码的宽度，单位 px，最小 280px，最大 1280px
	Width *int32 `json:"width,omitempty"`
	// false 否 自动配置线条颜色，如果颜色依然是黑色，则说明不建议配置主色调，默认 false
	AutoColor *bool                          `json:"auto_color,omitempty"`
	LineColor *GetwxacodeunlimitReqLineColor `json:"line_color,omitempty"`
	// false 否 是否需要透明底色，为 true 时，生成透明底色的小程序
	IsHyaline *bool `json:"is_hyaline,omitempty"`
}

// NewGetwxacodeunlimitReq instantiates a new GetwxacodeunlimitReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetwxacodeunlimitReq() *GetwxacodeunlimitReq {
	this := GetwxacodeunlimitReq{}
	return &this
}

// NewGetwxacodeunlimitReqWithDefaults instantiates a new GetwxacodeunlimitReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetwxacodeunlimitReqWithDefaults() *GetwxacodeunlimitReq {
	this := GetwxacodeunlimitReq{}
	return &this
}

// GetScene returns the Scene field value if set, zero value otherwise.
func (o *GetwxacodeunlimitReq) GetScene() string {
	if o == nil || isNil(o.Scene) {
		var ret string
		return ret
	}
	return *o.Scene
}

// GetSceneOk returns a tuple with the Scene field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetwxacodeunlimitReq) GetSceneOk() (*string, bool) {
	if o == nil || isNil(o.Scene) {
		return nil, false
	}
	return o.Scene, true
}

// HasScene returns a boolean if a field has been set.
func (o *GetwxacodeunlimitReq) HasScene() bool {
	if o != nil && !isNil(o.Scene) {
		return true
	}

	return false
}

// SetScene gets a reference to the given string and assigns it to the Scene field.
func (o *GetwxacodeunlimitReq) SetScene(v string) {
	o.Scene = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *GetwxacodeunlimitReq) GetPage() string {
	if o == nil || isNil(o.Page) {
		var ret string
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetwxacodeunlimitReq) GetPageOk() (*string, bool) {
	if o == nil || isNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *GetwxacodeunlimitReq) HasPage() bool {
	if o != nil && !isNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given string and assigns it to the Page field.
func (o *GetwxacodeunlimitReq) SetPage(v string) {
	o.Page = &v
}

// GetCheckPath returns the CheckPath field value if set, zero value otherwise.
func (o *GetwxacodeunlimitReq) GetCheckPath() bool {
	if o == nil || isNil(o.CheckPath) {
		var ret bool
		return ret
	}
	return *o.CheckPath
}

// GetCheckPathOk returns a tuple with the CheckPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetwxacodeunlimitReq) GetCheckPathOk() (*bool, bool) {
	if o == nil || isNil(o.CheckPath) {
		return nil, false
	}
	return o.CheckPath, true
}

// HasCheckPath returns a boolean if a field has been set.
func (o *GetwxacodeunlimitReq) HasCheckPath() bool {
	if o != nil && !isNil(o.CheckPath) {
		return true
	}

	return false
}

// SetCheckPath gets a reference to the given bool and assigns it to the CheckPath field.
func (o *GetwxacodeunlimitReq) SetCheckPath(v bool) {
	o.CheckPath = &v
}

// GetEnvVersion returns the EnvVersion field value if set, zero value otherwise.
func (o *GetwxacodeunlimitReq) GetEnvVersion() string {
	if o == nil || isNil(o.EnvVersion) {
		var ret string
		return ret
	}
	return *o.EnvVersion
}

// GetEnvVersionOk returns a tuple with the EnvVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetwxacodeunlimitReq) GetEnvVersionOk() (*string, bool) {
	if o == nil || isNil(o.EnvVersion) {
		return nil, false
	}
	return o.EnvVersion, true
}

// HasEnvVersion returns a boolean if a field has been set.
func (o *GetwxacodeunlimitReq) HasEnvVersion() bool {
	if o != nil && !isNil(o.EnvVersion) {
		return true
	}

	return false
}

// SetEnvVersion gets a reference to the given string and assigns it to the EnvVersion field.
func (o *GetwxacodeunlimitReq) SetEnvVersion(v string) {
	o.EnvVersion = &v
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *GetwxacodeunlimitReq) GetWidth() int32 {
	if o == nil || isNil(o.Width) {
		var ret int32
		return ret
	}
	return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetwxacodeunlimitReq) GetWidthOk() (*int32, bool) {
	if o == nil || isNil(o.Width) {
		return nil, false
	}
	return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *GetwxacodeunlimitReq) HasWidth() bool {
	if o != nil && !isNil(o.Width) {
		return true
	}

	return false
}

// SetWidth gets a reference to the given int32 and assigns it to the Width field.
func (o *GetwxacodeunlimitReq) SetWidth(v int32) {
	o.Width = &v
}

// GetAutoColor returns the AutoColor field value if set, zero value otherwise.
func (o *GetwxacodeunlimitReq) GetAutoColor() bool {
	if o == nil || isNil(o.AutoColor) {
		var ret bool
		return ret
	}
	return *o.AutoColor
}

// GetAutoColorOk returns a tuple with the AutoColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetwxacodeunlimitReq) GetAutoColorOk() (*bool, bool) {
	if o == nil || isNil(o.AutoColor) {
		return nil, false
	}
	return o.AutoColor, true
}

// HasAutoColor returns a boolean if a field has been set.
func (o *GetwxacodeunlimitReq) HasAutoColor() bool {
	if o != nil && !isNil(o.AutoColor) {
		return true
	}

	return false
}

// SetAutoColor gets a reference to the given bool and assigns it to the AutoColor field.
func (o *GetwxacodeunlimitReq) SetAutoColor(v bool) {
	o.AutoColor = &v
}

// GetLineColor returns the LineColor field value if set, zero value otherwise.
func (o *GetwxacodeunlimitReq) GetLineColor() GetwxacodeunlimitReqLineColor {
	if o == nil || isNil(o.LineColor) {
		var ret GetwxacodeunlimitReqLineColor
		return ret
	}
	return *o.LineColor
}

// GetLineColorOk returns a tuple with the LineColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetwxacodeunlimitReq) GetLineColorOk() (*GetwxacodeunlimitReqLineColor, bool) {
	if o == nil || isNil(o.LineColor) {
		return nil, false
	}
	return o.LineColor, true
}

// HasLineColor returns a boolean if a field has been set.
func (o *GetwxacodeunlimitReq) HasLineColor() bool {
	if o != nil && !isNil(o.LineColor) {
		return true
	}

	return false
}

// SetLineColor gets a reference to the given GetwxacodeunlimitReqLineColor and assigns it to the LineColor field.
func (o *GetwxacodeunlimitReq) SetLineColor(v GetwxacodeunlimitReqLineColor) {
	o.LineColor = &v
}

// GetIsHyaline returns the IsHyaline field value if set, zero value otherwise.
func (o *GetwxacodeunlimitReq) GetIsHyaline() bool {
	if o == nil || isNil(o.IsHyaline) {
		var ret bool
		return ret
	}
	return *o.IsHyaline
}

// GetIsHyalineOk returns a tuple with the IsHyaline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetwxacodeunlimitReq) GetIsHyalineOk() (*bool, bool) {
	if o == nil || isNil(o.IsHyaline) {
		return nil, false
	}
	return o.IsHyaline, true
}

// HasIsHyaline returns a boolean if a field has been set.
func (o *GetwxacodeunlimitReq) HasIsHyaline() bool {
	if o != nil && !isNil(o.IsHyaline) {
		return true
	}

	return false
}

// SetIsHyaline gets a reference to the given bool and assigns it to the IsHyaline field.
func (o *GetwxacodeunlimitReq) SetIsHyaline(v bool) {
	o.IsHyaline = &v
}

func (o GetwxacodeunlimitReq) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetwxacodeunlimitReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Scene) {
		toSerialize["scene"] = o.Scene
	}
	if !isNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !isNil(o.CheckPath) {
		toSerialize["check_path"] = o.CheckPath
	}
	if !isNil(o.EnvVersion) {
		toSerialize["env_version"] = o.EnvVersion
	}
	if !isNil(o.Width) {
		toSerialize["width"] = o.Width
	}
	if !isNil(o.AutoColor) {
		toSerialize["auto_color"] = o.AutoColor
	}
	if !isNil(o.LineColor) {
		toSerialize["line_color"] = o.LineColor
	}
	if !isNil(o.IsHyaline) {
		toSerialize["is_hyaline"] = o.IsHyaline
	}
	return toSerialize, nil
}

type NullableGetwxacodeunlimitReq struct {
	value *GetwxacodeunlimitReq
	isSet bool
}

func (v NullableGetwxacodeunlimitReq) Get() *GetwxacodeunlimitReq {
	return v.value
}

func (v *NullableGetwxacodeunlimitReq) Set(val *GetwxacodeunlimitReq) {
	v.value = val
	v.isSet = true
}

func (v NullableGetwxacodeunlimitReq) IsSet() bool {
	return v.isSet
}

func (v *NullableGetwxacodeunlimitReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetwxacodeunlimitReq(val *GetwxacodeunlimitReq) *NullableGetwxacodeunlimitReq {
	return &NullableGetwxacodeunlimitReq{value: val, isSet: true}
}

func (v NullableGetwxacodeunlimitReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetwxacodeunlimitReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
