/*
微信小程序相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package miniprogram

import (
	"encoding/json"
)

// checks if the GetwxacodeunlimitRsp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetwxacodeunlimitRsp{}

// GetwxacodeunlimitRsp struct for GetwxacodeunlimitRsp
type GetwxacodeunlimitRsp struct {
	// 返回码
	Errcode *int32 `json:"errcode,omitempty"`
	// 对返回码的文本描述内容
	Errmsg *string `json:"errmsg,omitempty"`
}

// NewGetwxacodeunlimitRsp instantiates a new GetwxacodeunlimitRsp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetwxacodeunlimitRsp() *GetwxacodeunlimitRsp {
	this := GetwxacodeunlimitRsp{}
	return &this
}

// NewGetwxacodeunlimitRspWithDefaults instantiates a new GetwxacodeunlimitRsp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetwxacodeunlimitRspWithDefaults() *GetwxacodeunlimitRsp {
	this := GetwxacodeunlimitRsp{}
	return &this
}

// GetErrcode returns the Errcode field value if set, zero value otherwise.
func (o *GetwxacodeunlimitRsp) GetErrcode() int32 {
	if o == nil || isNil(o.Errcode) {
		var ret int32
		return ret
	}
	return *o.Errcode
}

// GetErrcodeOk returns a tuple with the Errcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetwxacodeunlimitRsp) GetErrcodeOk() (*int32, bool) {
	if o == nil || isNil(o.Errcode) {
		return nil, false
	}
	return o.Errcode, true
}

// HasErrcode returns a boolean if a field has been set.
func (o *GetwxacodeunlimitRsp) HasErrcode() bool {
	if o != nil && !isNil(o.Errcode) {
		return true
	}

	return false
}

// SetErrcode gets a reference to the given int32 and assigns it to the Errcode field.
func (o *GetwxacodeunlimitRsp) SetErrcode(v int32) {
	o.Errcode = &v
}

// GetErrmsg returns the Errmsg field value if set, zero value otherwise.
func (o *GetwxacodeunlimitRsp) GetErrmsg() string {
	if o == nil || isNil(o.Errmsg) {
		var ret string
		return ret
	}
	return *o.Errmsg
}

// GetErrmsgOk returns a tuple with the Errmsg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetwxacodeunlimitRsp) GetErrmsgOk() (*string, bool) {
	if o == nil || isNil(o.Errmsg) {
		return nil, false
	}
	return o.Errmsg, true
}

// HasErrmsg returns a boolean if a field has been set.
func (o *GetwxacodeunlimitRsp) HasErrmsg() bool {
	if o != nil && !isNil(o.Errmsg) {
		return true
	}

	return false
}

// SetErrmsg gets a reference to the given string and assigns it to the Errmsg field.
func (o *GetwxacodeunlimitRsp) SetErrmsg(v string) {
	o.Errmsg = &v
}

func (o GetwxacodeunlimitRsp) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetwxacodeunlimitRsp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Errcode) {
		toSerialize["errcode"] = o.Errcode
	}
	if !isNil(o.Errmsg) {
		toSerialize["errmsg"] = o.Errmsg
	}
	return toSerialize, nil
}

type NullableGetwxacodeunlimitRsp struct {
	value *GetwxacodeunlimitRsp
	isSet bool
}

func (v NullableGetwxacodeunlimitRsp) Get() *GetwxacodeunlimitRsp {
	return v.value
}

func (v *NullableGetwxacodeunlimitRsp) Set(val *GetwxacodeunlimitRsp) {
	v.value = val
	v.isSet = true
}

func (v NullableGetwxacodeunlimitRsp) IsSet() bool {
	return v.isSet
}

func (v *NullableGetwxacodeunlimitRsp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetwxacodeunlimitRsp(val *GetwxacodeunlimitRsp) *NullableGetwxacodeunlimitRsp {
	return &NullableGetwxacodeunlimitRsp{value: val, isSet: true}
}

func (v NullableGetwxacodeunlimitRsp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetwxacodeunlimitRsp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
