/*
微信第三方平台授权相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package third_part_auth

import (
	"encoding/json"
)

// checks if the GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork{}

// GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork struct for GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork
type GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork struct {
	RequestDomain   []string `json:"RequestDomain,omitempty"`
	WsRequestDomain []string `json:"WsRequestDomain,omitempty"`
	UploadDomain    []string `json:"UploadDomain,omitempty"`
	DownloadDomain  []string `json:"DownloadDomain,omitempty"`
	BizDomain       []string `json:"BizDomain,omitempty"`
	UDPDomain       []string `json:"UDPDomain,omitempty"`
}

// NewGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork instantiates a new GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork() *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork {
	this := GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork{}
	return &this
}

// NewGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetworkWithDefaults instantiates a new GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetworkWithDefaults() *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork {
	this := GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork{}
	return &this
}

// GetRequestDomain returns the RequestDomain field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) GetRequestDomain() []string {
	if o == nil || isNil(o.RequestDomain) {
		var ret []string
		return ret
	}
	return o.RequestDomain
}

// GetRequestDomainOk returns a tuple with the RequestDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) GetRequestDomainOk() ([]string, bool) {
	if o == nil || isNil(o.RequestDomain) {
		return nil, false
	}
	return o.RequestDomain, true
}

// HasRequestDomain returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) HasRequestDomain() bool {
	if o != nil && !isNil(o.RequestDomain) {
		return true
	}

	return false
}

// SetRequestDomain gets a reference to the given []string and assigns it to the RequestDomain field.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) SetRequestDomain(v []string) {
	o.RequestDomain = v
}

// GetWsRequestDomain returns the WsRequestDomain field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) GetWsRequestDomain() []string {
	if o == nil || isNil(o.WsRequestDomain) {
		var ret []string
		return ret
	}
	return o.WsRequestDomain
}

// GetWsRequestDomainOk returns a tuple with the WsRequestDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) GetWsRequestDomainOk() ([]string, bool) {
	if o == nil || isNil(o.WsRequestDomain) {
		return nil, false
	}
	return o.WsRequestDomain, true
}

// HasWsRequestDomain returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) HasWsRequestDomain() bool {
	if o != nil && !isNil(o.WsRequestDomain) {
		return true
	}

	return false
}

// SetWsRequestDomain gets a reference to the given []string and assigns it to the WsRequestDomain field.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) SetWsRequestDomain(v []string) {
	o.WsRequestDomain = v
}

// GetUploadDomain returns the UploadDomain field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) GetUploadDomain() []string {
	if o == nil || isNil(o.UploadDomain) {
		var ret []string
		return ret
	}
	return o.UploadDomain
}

// GetUploadDomainOk returns a tuple with the UploadDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) GetUploadDomainOk() ([]string, bool) {
	if o == nil || isNil(o.UploadDomain) {
		return nil, false
	}
	return o.UploadDomain, true
}

// HasUploadDomain returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) HasUploadDomain() bool {
	if o != nil && !isNil(o.UploadDomain) {
		return true
	}

	return false
}

// SetUploadDomain gets a reference to the given []string and assigns it to the UploadDomain field.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) SetUploadDomain(v []string) {
	o.UploadDomain = v
}

// GetDownloadDomain returns the DownloadDomain field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) GetDownloadDomain() []string {
	if o == nil || isNil(o.DownloadDomain) {
		var ret []string
		return ret
	}
	return o.DownloadDomain
}

// GetDownloadDomainOk returns a tuple with the DownloadDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) GetDownloadDomainOk() ([]string, bool) {
	if o == nil || isNil(o.DownloadDomain) {
		return nil, false
	}
	return o.DownloadDomain, true
}

// HasDownloadDomain returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) HasDownloadDomain() bool {
	if o != nil && !isNil(o.DownloadDomain) {
		return true
	}

	return false
}

// SetDownloadDomain gets a reference to the given []string and assigns it to the DownloadDomain field.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) SetDownloadDomain(v []string) {
	o.DownloadDomain = v
}

// GetBizDomain returns the BizDomain field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) GetBizDomain() []string {
	if o == nil || isNil(o.BizDomain) {
		var ret []string
		return ret
	}
	return o.BizDomain
}

// GetBizDomainOk returns a tuple with the BizDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) GetBizDomainOk() ([]string, bool) {
	if o == nil || isNil(o.BizDomain) {
		return nil, false
	}
	return o.BizDomain, true
}

// HasBizDomain returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) HasBizDomain() bool {
	if o != nil && !isNil(o.BizDomain) {
		return true
	}

	return false
}

// SetBizDomain gets a reference to the given []string and assigns it to the BizDomain field.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) SetBizDomain(v []string) {
	o.BizDomain = v
}

// GetUDPDomain returns the UDPDomain field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) GetUDPDomain() []string {
	if o == nil || isNil(o.UDPDomain) {
		var ret []string
		return ret
	}
	return o.UDPDomain
}

// GetUDPDomainOk returns a tuple with the UDPDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) GetUDPDomainOk() ([]string, bool) {
	if o == nil || isNil(o.UDPDomain) {
		return nil, false
	}
	return o.UDPDomain, true
}

// HasUDPDomain returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) HasUDPDomain() bool {
	if o != nil && !isNil(o.UDPDomain) {
		return true
	}

	return false
}

// SetUDPDomain gets a reference to the given []string and assigns it to the UDPDomain field.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) SetUDPDomain(v []string) {
	o.UDPDomain = v
}

func (o GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.RequestDomain) {
		toSerialize["RequestDomain"] = o.RequestDomain
	}
	if !isNil(o.WsRequestDomain) {
		toSerialize["WsRequestDomain"] = o.WsRequestDomain
	}
	if !isNil(o.UploadDomain) {
		toSerialize["UploadDomain"] = o.UploadDomain
	}
	if !isNil(o.DownloadDomain) {
		toSerialize["DownloadDomain"] = o.DownloadDomain
	}
	if !isNil(o.BizDomain) {
		toSerialize["BizDomain"] = o.BizDomain
	}
	if !isNil(o.UDPDomain) {
		toSerialize["UDPDomain"] = o.UDPDomain
	}
	return toSerialize, nil
}

type NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork struct {
	value *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork
	isSet bool
}

func (v NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) Get() *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork {
	return v.value
}

func (v *NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) Set(val *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork(val *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) *NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork {
	return &NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork{value: val, isSet: true}
}

func (v NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
