/*
微信第三方平台授权相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package third_part_auth

import (
	"encoding/json"
)

// checks if the StartPushTicketResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StartPushTicketResponse{}

// StartPushTicketResponse struct for StartPushTicketResponse
type StartPushTicketResponse struct {
	// 返回码
	Errcode *int32 `json:"errcode,omitempty"`
	// 对返回码的文本描述内容
	Errmsg *string `json:"errmsg,omitempty"`
}

// NewStartPushTicketResponse instantiates a new StartPushTicketResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStartPushTicketResponse() *StartPushTicketResponse {
	this := StartPushTicketResponse{}
	return &this
}

// NewStartPushTicketResponseWithDefaults instantiates a new StartPushTicketResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStartPushTicketResponseWithDefaults() *StartPushTicketResponse {
	this := StartPushTicketResponse{}
	return &this
}

// GetErrcode returns the Errcode field value if set, zero value otherwise.
func (o *StartPushTicketResponse) GetErrcode() int32 {
	if o == nil || isNil(o.Errcode) {
		var ret int32
		return ret
	}
	return *o.Errcode
}

// GetErrcodeOk returns a tuple with the Errcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartPushTicketResponse) GetErrcodeOk() (*int32, bool) {
	if o == nil || isNil(o.Errcode) {
		return nil, false
	}
	return o.Errcode, true
}

// HasErrcode returns a boolean if a field has been set.
func (o *StartPushTicketResponse) HasErrcode() bool {
	if o != nil && !isNil(o.Errcode) {
		return true
	}

	return false
}

// SetErrcode gets a reference to the given int32 and assigns it to the Errcode field.
func (o *StartPushTicketResponse) SetErrcode(v int32) {
	o.Errcode = &v
}

// GetErrmsg returns the Errmsg field value if set, zero value otherwise.
func (o *StartPushTicketResponse) GetErrmsg() string {
	if o == nil || isNil(o.Errmsg) {
		var ret string
		return ret
	}
	return *o.Errmsg
}

// GetErrmsgOk returns a tuple with the Errmsg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartPushTicketResponse) GetErrmsgOk() (*string, bool) {
	if o == nil || isNil(o.Errmsg) {
		return nil, false
	}
	return o.Errmsg, true
}

// HasErrmsg returns a boolean if a field has been set.
func (o *StartPushTicketResponse) HasErrmsg() bool {
	if o != nil && !isNil(o.Errmsg) {
		return true
	}

	return false
}

// SetErrmsg gets a reference to the given string and assigns it to the Errmsg field.
func (o *StartPushTicketResponse) SetErrmsg(v string) {
	o.Errmsg = &v
}

func (o StartPushTicketResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StartPushTicketResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Errcode) {
		toSerialize["errcode"] = o.Errcode
	}
	if !isNil(o.Errmsg) {
		toSerialize["errmsg"] = o.Errmsg
	}
	return toSerialize, nil
}

type NullableStartPushTicketResponse struct {
	value *StartPushTicketResponse
	isSet bool
}

func (v NullableStartPushTicketResponse) Get() *StartPushTicketResponse {
	return v.value
}

func (v *NullableStartPushTicketResponse) Set(val *StartPushTicketResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStartPushTicketResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStartPushTicketResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStartPushTicketResponse(val *StartPushTicketResponse) *NullableStartPushTicketResponse {
	return &NullableStartPushTicketResponse{value: val, isSet: true}
}

func (v NullableStartPushTicketResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStartPushTicketResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
