/*
微信第三方平台授权相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package third_part_auth

import (
	"encoding/json"
)

// checks if the ComponentTokenRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComponentTokenRequest{}

// ComponentTokenRequest struct for ComponentTokenRequest
type ComponentTokenRequest struct {
	// 平台型第三方平台的appid
	ComponentAppid string `json:"component_appid"`
	// 第三方平台 appsecret
	ComponentAppsecret string `json:"component_appsecret"`
	// 微信后台推送的 ticket
	ComponentVerifyTicket string `json:"component_verify_ticket"`
}

// NewComponentTokenRequest instantiates a new ComponentTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComponentTokenRequest(componentAppid string, componentAppsecret string, componentVerifyTicket string) *ComponentTokenRequest {
	this := ComponentTokenRequest{}
	this.ComponentAppid = componentAppid
	this.ComponentAppsecret = componentAppsecret
	this.ComponentVerifyTicket = componentVerifyTicket
	return &this
}

// NewComponentTokenRequestWithDefaults instantiates a new ComponentTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComponentTokenRequestWithDefaults() *ComponentTokenRequest {
	this := ComponentTokenRequest{}
	return &this
}

// GetComponentAppid returns the ComponentAppid field value
func (o *ComponentTokenRequest) GetComponentAppid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ComponentAppid
}

// GetComponentAppidOk returns a tuple with the ComponentAppid field value
// and a boolean to check if the value has been set.
func (o *ComponentTokenRequest) GetComponentAppidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ComponentAppid, true
}

// SetComponentAppid sets field value
func (o *ComponentTokenRequest) SetComponentAppid(v string) {
	o.ComponentAppid = v
}

// GetComponentAppsecret returns the ComponentAppsecret field value
func (o *ComponentTokenRequest) GetComponentAppsecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ComponentAppsecret
}

// GetComponentAppsecretOk returns a tuple with the ComponentAppsecret field value
// and a boolean to check if the value has been set.
func (o *ComponentTokenRequest) GetComponentAppsecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ComponentAppsecret, true
}

// SetComponentAppsecret sets field value
func (o *ComponentTokenRequest) SetComponentAppsecret(v string) {
	o.ComponentAppsecret = v
}

// GetComponentVerifyTicket returns the ComponentVerifyTicket field value
func (o *ComponentTokenRequest) GetComponentVerifyTicket() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ComponentVerifyTicket
}

// GetComponentVerifyTicketOk returns a tuple with the ComponentVerifyTicket field value
// and a boolean to check if the value has been set.
func (o *ComponentTokenRequest) GetComponentVerifyTicketOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ComponentVerifyTicket, true
}

// SetComponentVerifyTicket sets field value
func (o *ComponentTokenRequest) SetComponentVerifyTicket(v string) {
	o.ComponentVerifyTicket = v
}

func (o ComponentTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComponentTokenRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["component_appid"] = o.ComponentAppid
	toSerialize["component_appsecret"] = o.ComponentAppsecret
	toSerialize["component_verify_ticket"] = o.ComponentVerifyTicket
	return toSerialize, nil
}

type NullableComponentTokenRequest struct {
	value *ComponentTokenRequest
	isSet bool
}

func (v NullableComponentTokenRequest) Get() *ComponentTokenRequest {
	return v.value
}

func (v *NullableComponentTokenRequest) Set(val *ComponentTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableComponentTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableComponentTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComponentTokenRequest(val *ComponentTokenRequest) *NullableComponentTokenRequest {
	return &NullableComponentTokenRequest{value: val, isSet: true}
}

func (v NullableComponentTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComponentTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
