/*
微信第三方平台授权相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package third_part_auth

import (
	"encoding/json"
)

// checks if the GetAuthorizerInfoRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAuthorizerInfoRequest{}

// GetAuthorizerInfoRequest struct for GetAuthorizerInfoRequest
type GetAuthorizerInfoRequest struct {
	// 平台型第三方平台的appid
	ComponentAppid string `json:"component_appid"`
	// 授权方 appid
	AuthorizerAppid string `json:"authorizer_appid"`
}

// NewGetAuthorizerInfoRequest instantiates a new GetAuthorizerInfoRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAuthorizerInfoRequest(componentAppid string, authorizerAppid string) *GetAuthorizerInfoRequest {
	this := GetAuthorizerInfoRequest{}
	this.ComponentAppid = componentAppid
	this.AuthorizerAppid = authorizerAppid
	return &this
}

// NewGetAuthorizerInfoRequestWithDefaults instantiates a new GetAuthorizerInfoRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAuthorizerInfoRequestWithDefaults() *GetAuthorizerInfoRequest {
	this := GetAuthorizerInfoRequest{}
	return &this
}

// GetComponentAppid returns the ComponentAppid field value
func (o *GetAuthorizerInfoRequest) GetComponentAppid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ComponentAppid
}

// GetComponentAppidOk returns a tuple with the ComponentAppid field value
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoRequest) GetComponentAppidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ComponentAppid, true
}

// SetComponentAppid sets field value
func (o *GetAuthorizerInfoRequest) SetComponentAppid(v string) {
	o.ComponentAppid = v
}

// GetAuthorizerAppid returns the AuthorizerAppid field value
func (o *GetAuthorizerInfoRequest) GetAuthorizerAppid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthorizerAppid
}

// GetAuthorizerAppidOk returns a tuple with the AuthorizerAppid field value
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoRequest) GetAuthorizerAppidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthorizerAppid, true
}

// SetAuthorizerAppid sets field value
func (o *GetAuthorizerInfoRequest) SetAuthorizerAppid(v string) {
	o.AuthorizerAppid = v
}

func (o GetAuthorizerInfoRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAuthorizerInfoRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["component_appid"] = o.ComponentAppid
	toSerialize["authorizer_appid"] = o.AuthorizerAppid
	return toSerialize, nil
}

type NullableGetAuthorizerInfoRequest struct {
	value *GetAuthorizerInfoRequest
	isSet bool
}

func (v NullableGetAuthorizerInfoRequest) Get() *GetAuthorizerInfoRequest {
	return v.value
}

func (v *NullableGetAuthorizerInfoRequest) Set(val *GetAuthorizerInfoRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAuthorizerInfoRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAuthorizerInfoRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAuthorizerInfoRequest(val *GetAuthorizerInfoRequest) *NullableGetAuthorizerInfoRequest {
	return &NullableGetAuthorizerInfoRequest{value: val, isSet: true}
}

func (v NullableGetAuthorizerInfoRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAuthorizerInfoRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
