/*
微信第三方平台授权相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package third_part_auth

import (
	"encoding/json"
)

// checks if the QueryAuthResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryAuthResponse{}

// QueryAuthResponse struct for QueryAuthResponse
type QueryAuthResponse struct {
	// 返回码
	Errcode *int32 `json:"errcode,omitempty"`
	// 对返回码的文本描述内容
	Errmsg            *string                             `json:"errmsg,omitempty"`
	AuthorizationInfo *QueryAuthResponseAuthorizationInfo `json:"authorization_info,omitempty"`
}

// NewQueryAuthResponse instantiates a new QueryAuthResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryAuthResponse() *QueryAuthResponse {
	this := QueryAuthResponse{}
	return &this
}

// NewQueryAuthResponseWithDefaults instantiates a new QueryAuthResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryAuthResponseWithDefaults() *QueryAuthResponse {
	this := QueryAuthResponse{}
	return &this
}

// GetErrcode returns the Errcode field value if set, zero value otherwise.
func (o *QueryAuthResponse) GetErrcode() int32 {
	if o == nil || isNil(o.Errcode) {
		var ret int32
		return ret
	}
	return *o.Errcode
}

// GetErrcodeOk returns a tuple with the Errcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryAuthResponse) GetErrcodeOk() (*int32, bool) {
	if o == nil || isNil(o.Errcode) {
		return nil, false
	}
	return o.Errcode, true
}

// HasErrcode returns a boolean if a field has been set.
func (o *QueryAuthResponse) HasErrcode() bool {
	if o != nil && !isNil(o.Errcode) {
		return true
	}

	return false
}

// SetErrcode gets a reference to the given int32 and assigns it to the Errcode field.
func (o *QueryAuthResponse) SetErrcode(v int32) {
	o.Errcode = &v
}

// GetErrmsg returns the Errmsg field value if set, zero value otherwise.
func (o *QueryAuthResponse) GetErrmsg() string {
	if o == nil || isNil(o.Errmsg) {
		var ret string
		return ret
	}
	return *o.Errmsg
}

// GetErrmsgOk returns a tuple with the Errmsg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryAuthResponse) GetErrmsgOk() (*string, bool) {
	if o == nil || isNil(o.Errmsg) {
		return nil, false
	}
	return o.Errmsg, true
}

// HasErrmsg returns a boolean if a field has been set.
func (o *QueryAuthResponse) HasErrmsg() bool {
	if o != nil && !isNil(o.Errmsg) {
		return true
	}

	return false
}

// SetErrmsg gets a reference to the given string and assigns it to the Errmsg field.
func (o *QueryAuthResponse) SetErrmsg(v string) {
	o.Errmsg = &v
}

// GetAuthorizationInfo returns the AuthorizationInfo field value if set, zero value otherwise.
func (o *QueryAuthResponse) GetAuthorizationInfo() QueryAuthResponseAuthorizationInfo {
	if o == nil || isNil(o.AuthorizationInfo) {
		var ret QueryAuthResponseAuthorizationInfo
		return ret
	}
	return *o.AuthorizationInfo
}

// GetAuthorizationInfoOk returns a tuple with the AuthorizationInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryAuthResponse) GetAuthorizationInfoOk() (*QueryAuthResponseAuthorizationInfo, bool) {
	if o == nil || isNil(o.AuthorizationInfo) {
		return nil, false
	}
	return o.AuthorizationInfo, true
}

// HasAuthorizationInfo returns a boolean if a field has been set.
func (o *QueryAuthResponse) HasAuthorizationInfo() bool {
	if o != nil && !isNil(o.AuthorizationInfo) {
		return true
	}

	return false
}

// SetAuthorizationInfo gets a reference to the given QueryAuthResponseAuthorizationInfo and assigns it to the AuthorizationInfo field.
func (o *QueryAuthResponse) SetAuthorizationInfo(v QueryAuthResponseAuthorizationInfo) {
	o.AuthorizationInfo = &v
}

func (o QueryAuthResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryAuthResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Errcode) {
		toSerialize["errcode"] = o.Errcode
	}
	if !isNil(o.Errmsg) {
		toSerialize["errmsg"] = o.Errmsg
	}
	if !isNil(o.AuthorizationInfo) {
		toSerialize["authorization_info"] = o.AuthorizationInfo
	}
	return toSerialize, nil
}

type NullableQueryAuthResponse struct {
	value *QueryAuthResponse
	isSet bool
}

func (v NullableQueryAuthResponse) Get() *QueryAuthResponse {
	return v.value
}

func (v *NullableQueryAuthResponse) Set(val *QueryAuthResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryAuthResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryAuthResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryAuthResponse(val *QueryAuthResponse) *NullableQueryAuthResponse {
	return &NullableQueryAuthResponse{value: val, isSet: true}
}

func (v NullableQueryAuthResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryAuthResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
