/*
微信第三方平台授权相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package third_part_auth

import (
	"encoding/json"
)

// checks if the ComponentTokenResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComponentTokenResponse{}

// ComponentTokenResponse struct for ComponentTokenResponse
type ComponentTokenResponse struct {
	// 返回码
	Errcode *int32 `json:"errcode,omitempty"`
	// 对返回码的文本描述内容
	Errmsg *string `json:"errmsg,omitempty"`
	// 有效期，单位：秒
	ExpiresIn *int32 `json:"expires_in,omitempty"`
	// 第三方平台 access_token
	ComponentAccessToken *string `json:"component_access_token,omitempty"`
}

// NewComponentTokenResponse instantiates a new ComponentTokenResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComponentTokenResponse() *ComponentTokenResponse {
	this := ComponentTokenResponse{}
	return &this
}

// NewComponentTokenResponseWithDefaults instantiates a new ComponentTokenResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComponentTokenResponseWithDefaults() *ComponentTokenResponse {
	this := ComponentTokenResponse{}
	return &this
}

// GetErrcode returns the Errcode field value if set, zero value otherwise.
func (o *ComponentTokenResponse) GetErrcode() int32 {
	if o == nil || isNil(o.Errcode) {
		var ret int32
		return ret
	}
	return *o.Errcode
}

// GetErrcodeOk returns a tuple with the Errcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentTokenResponse) GetErrcodeOk() (*int32, bool) {
	if o == nil || isNil(o.Errcode) {
		return nil, false
	}
	return o.Errcode, true
}

// HasErrcode returns a boolean if a field has been set.
func (o *ComponentTokenResponse) HasErrcode() bool {
	if o != nil && !isNil(o.Errcode) {
		return true
	}

	return false
}

// SetErrcode gets a reference to the given int32 and assigns it to the Errcode field.
func (o *ComponentTokenResponse) SetErrcode(v int32) {
	o.Errcode = &v
}

// GetErrmsg returns the Errmsg field value if set, zero value otherwise.
func (o *ComponentTokenResponse) GetErrmsg() string {
	if o == nil || isNil(o.Errmsg) {
		var ret string
		return ret
	}
	return *o.Errmsg
}

// GetErrmsgOk returns a tuple with the Errmsg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentTokenResponse) GetErrmsgOk() (*string, bool) {
	if o == nil || isNil(o.Errmsg) {
		return nil, false
	}
	return o.Errmsg, true
}

// HasErrmsg returns a boolean if a field has been set.
func (o *ComponentTokenResponse) HasErrmsg() bool {
	if o != nil && !isNil(o.Errmsg) {
		return true
	}

	return false
}

// SetErrmsg gets a reference to the given string and assigns it to the Errmsg field.
func (o *ComponentTokenResponse) SetErrmsg(v string) {
	o.Errmsg = &v
}

// GetExpiresIn returns the ExpiresIn field value if set, zero value otherwise.
func (o *ComponentTokenResponse) GetExpiresIn() int32 {
	if o == nil || isNil(o.ExpiresIn) {
		var ret int32
		return ret
	}
	return *o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentTokenResponse) GetExpiresInOk() (*int32, bool) {
	if o == nil || isNil(o.ExpiresIn) {
		return nil, false
	}
	return o.ExpiresIn, true
}

// HasExpiresIn returns a boolean if a field has been set.
func (o *ComponentTokenResponse) HasExpiresIn() bool {
	if o != nil && !isNil(o.ExpiresIn) {
		return true
	}

	return false
}

// SetExpiresIn gets a reference to the given int32 and assigns it to the ExpiresIn field.
func (o *ComponentTokenResponse) SetExpiresIn(v int32) {
	o.ExpiresIn = &v
}

// GetComponentAccessToken returns the ComponentAccessToken field value if set, zero value otherwise.
func (o *ComponentTokenResponse) GetComponentAccessToken() string {
	if o == nil || isNil(o.ComponentAccessToken) {
		var ret string
		return ret
	}
	return *o.ComponentAccessToken
}

// GetComponentAccessTokenOk returns a tuple with the ComponentAccessToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentTokenResponse) GetComponentAccessTokenOk() (*string, bool) {
	if o == nil || isNil(o.ComponentAccessToken) {
		return nil, false
	}
	return o.ComponentAccessToken, true
}

// HasComponentAccessToken returns a boolean if a field has been set.
func (o *ComponentTokenResponse) HasComponentAccessToken() bool {
	if o != nil && !isNil(o.ComponentAccessToken) {
		return true
	}

	return false
}

// SetComponentAccessToken gets a reference to the given string and assigns it to the ComponentAccessToken field.
func (o *ComponentTokenResponse) SetComponentAccessToken(v string) {
	o.ComponentAccessToken = &v
}

func (o ComponentTokenResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComponentTokenResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Errcode) {
		toSerialize["errcode"] = o.Errcode
	}
	if !isNil(o.Errmsg) {
		toSerialize["errmsg"] = o.Errmsg
	}
	if !isNil(o.ExpiresIn) {
		toSerialize["expires_in"] = o.ExpiresIn
	}
	if !isNil(o.ComponentAccessToken) {
		toSerialize["component_access_token"] = o.ComponentAccessToken
	}
	return toSerialize, nil
}

type NullableComponentTokenResponse struct {
	value *ComponentTokenResponse
	isSet bool
}

func (v NullableComponentTokenResponse) Get() *ComponentTokenResponse {
	return v.value
}

func (v *NullableComponentTokenResponse) Set(val *ComponentTokenResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableComponentTokenResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableComponentTokenResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComponentTokenResponse(val *ComponentTokenResponse) *NullableComponentTokenResponse {
	return &NullableComponentTokenResponse{value: val, isSet: true}
}

func (v NullableComponentTokenResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComponentTokenResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
