/*
微信第三方平台授权相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package third_part_auth

import (
	"encoding/json"
)

// checks if the AuthorizerTokenRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorizerTokenRequest{}

// AuthorizerTokenRequest struct for AuthorizerTokenRequest
type AuthorizerTokenRequest struct {
	// 平台型第三方平台的appid
	ComponentAppid string `json:"component_appid"`
	// 授权方 appid
	AuthorizerAppid string `json:"authorizer_appid"`
	// 刷新令牌，获取授权信息时得到
	AuthorizerRefreshToken string `json:"authorizer_refresh_token"`
}

// NewAuthorizerTokenRequest instantiates a new AuthorizerTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorizerTokenRequest(componentAppid string, authorizerAppid string, authorizerRefreshToken string) *AuthorizerTokenRequest {
	this := AuthorizerTokenRequest{}
	this.ComponentAppid = componentAppid
	this.AuthorizerAppid = authorizerAppid
	this.AuthorizerRefreshToken = authorizerRefreshToken
	return &this
}

// NewAuthorizerTokenRequestWithDefaults instantiates a new AuthorizerTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorizerTokenRequestWithDefaults() *AuthorizerTokenRequest {
	this := AuthorizerTokenRequest{}
	return &this
}

// GetComponentAppid returns the ComponentAppid field value
func (o *AuthorizerTokenRequest) GetComponentAppid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ComponentAppid
}

// GetComponentAppidOk returns a tuple with the ComponentAppid field value
// and a boolean to check if the value has been set.
func (o *AuthorizerTokenRequest) GetComponentAppidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ComponentAppid, true
}

// SetComponentAppid sets field value
func (o *AuthorizerTokenRequest) SetComponentAppid(v string) {
	o.ComponentAppid = v
}

// GetAuthorizerAppid returns the AuthorizerAppid field value
func (o *AuthorizerTokenRequest) GetAuthorizerAppid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthorizerAppid
}

// GetAuthorizerAppidOk returns a tuple with the AuthorizerAppid field value
// and a boolean to check if the value has been set.
func (o *AuthorizerTokenRequest) GetAuthorizerAppidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthorizerAppid, true
}

// SetAuthorizerAppid sets field value
func (o *AuthorizerTokenRequest) SetAuthorizerAppid(v string) {
	o.AuthorizerAppid = v
}

// GetAuthorizerRefreshToken returns the AuthorizerRefreshToken field value
func (o *AuthorizerTokenRequest) GetAuthorizerRefreshToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthorizerRefreshToken
}

// GetAuthorizerRefreshTokenOk returns a tuple with the AuthorizerRefreshToken field value
// and a boolean to check if the value has been set.
func (o *AuthorizerTokenRequest) GetAuthorizerRefreshTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthorizerRefreshToken, true
}

// SetAuthorizerRefreshToken sets field value
func (o *AuthorizerTokenRequest) SetAuthorizerRefreshToken(v string) {
	o.AuthorizerRefreshToken = v
}

func (o AuthorizerTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorizerTokenRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["component_appid"] = o.ComponentAppid
	toSerialize["authorizer_appid"] = o.AuthorizerAppid
	toSerialize["authorizer_refresh_token"] = o.AuthorizerRefreshToken
	return toSerialize, nil
}

type NullableAuthorizerTokenRequest struct {
	value *AuthorizerTokenRequest
	isSet bool
}

func (v NullableAuthorizerTokenRequest) Get() *AuthorizerTokenRequest {
	return v.value
}

func (v *NullableAuthorizerTokenRequest) Set(val *AuthorizerTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorizerTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorizerTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorizerTokenRequest(val *AuthorizerTokenRequest) *NullableAuthorizerTokenRequest {
	return &NullableAuthorizerTokenRequest{value: val, isSet: true}
}

func (v NullableAuthorizerTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorizerTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
