/*
微信第三方平台授权相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package third_part_auth

import (
	"encoding/json"
)

// checks if the GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo{}

// GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo 公众号类型
type GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo struct {
	Id *int32 `json:"id,omitempty"`
}

// NewGetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo instantiates a new GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo() *GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo {
	this := GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo{}
	return &this
}

// NewGetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfoWithDefaults instantiates a new GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfoWithDefaults() *GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo {
	this := GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo) GetId() int32 {
	if o == nil || isNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo) GetIdOk() (*int32, bool) {
	if o == nil || isNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo) SetId(v int32) {
	o.Id = &v
}

func (o GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableGetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo struct {
	value *GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo
	isSet bool
}

func (v NullableGetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo) Get() *GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo {
	return v.value
}

func (v *NullableGetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo) Set(val *GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo(val *GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo) *NullableGetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo {
	return &NullableGetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo{value: val, isSet: true}
}

func (v NullableGetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
