/*
微信第三方平台授权相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package third_part_auth

import (
	"encoding/json"
)

// checks if the QueryAuthRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryAuthRequest{}

// QueryAuthRequest struct for QueryAuthRequest
type QueryAuthRequest struct {
	// 平台型第三方平台的appid
	ComponentAppid string `json:"component_appid"`
	// 授权码, 会在授权成功时返回给第三方平台，详见第三方平台授权流程说明
	AuthorizationCode string `json:"authorization_code"`
}

// NewQueryAuthRequest instantiates a new QueryAuthRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryAuthRequest(componentAppid string, authorizationCode string) *QueryAuthRequest {
	this := QueryAuthRequest{}
	this.ComponentAppid = componentAppid
	this.AuthorizationCode = authorizationCode
	return &this
}

// NewQueryAuthRequestWithDefaults instantiates a new QueryAuthRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryAuthRequestWithDefaults() *QueryAuthRequest {
	this := QueryAuthRequest{}
	return &this
}

// GetComponentAppid returns the ComponentAppid field value
func (o *QueryAuthRequest) GetComponentAppid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ComponentAppid
}

// GetComponentAppidOk returns a tuple with the ComponentAppid field value
// and a boolean to check if the value has been set.
func (o *QueryAuthRequest) GetComponentAppidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ComponentAppid, true
}

// SetComponentAppid sets field value
func (o *QueryAuthRequest) SetComponentAppid(v string) {
	o.ComponentAppid = v
}

// GetAuthorizationCode returns the AuthorizationCode field value
func (o *QueryAuthRequest) GetAuthorizationCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthorizationCode
}

// GetAuthorizationCodeOk returns a tuple with the AuthorizationCode field value
// and a boolean to check if the value has been set.
func (o *QueryAuthRequest) GetAuthorizationCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthorizationCode, true
}

// SetAuthorizationCode sets field value
func (o *QueryAuthRequest) SetAuthorizationCode(v string) {
	o.AuthorizationCode = v
}

func (o QueryAuthRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryAuthRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["component_appid"] = o.ComponentAppid
	toSerialize["authorization_code"] = o.AuthorizationCode
	return toSerialize, nil
}

type NullableQueryAuthRequest struct {
	value *QueryAuthRequest
	isSet bool
}

func (v NullableQueryAuthRequest) Get() *QueryAuthRequest {
	return v.value
}

func (v *NullableQueryAuthRequest) Set(val *QueryAuthRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryAuthRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryAuthRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryAuthRequest(val *QueryAuthRequest) *NullableQueryAuthRequest {
	return &NullableQueryAuthRequest{value: val, isSet: true}
}

func (v NullableQueryAuthRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryAuthRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
