/*
微信第三方平台授权相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package third_part_auth

import (
	"encoding/json"
)

// checks if the GetAuthorizerInfoResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAuthorizerInfoResponse{}

// GetAuthorizerInfoResponse struct for GetAuthorizerInfoResponse
type GetAuthorizerInfoResponse struct {
	// 返回码
	Errcode *int32 `json:"errcode,omitempty"`
	// 对返回码的文本描述内容
	Errmsg            *string                                     `json:"errmsg,omitempty"`
	AuthorizerInfo    *GetAuthorizerInfoResponseAuthorizerInfo    `json:"authorizer_info,omitempty"`
	AuthorizationInfo *GetAuthorizerInfoResponseAuthorizationInfo `json:"authorization_info,omitempty"`
}

// NewGetAuthorizerInfoResponse instantiates a new GetAuthorizerInfoResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAuthorizerInfoResponse() *GetAuthorizerInfoResponse {
	this := GetAuthorizerInfoResponse{}
	return &this
}

// NewGetAuthorizerInfoResponseWithDefaults instantiates a new GetAuthorizerInfoResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAuthorizerInfoResponseWithDefaults() *GetAuthorizerInfoResponse {
	this := GetAuthorizerInfoResponse{}
	return &this
}

// GetErrcode returns the Errcode field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponse) GetErrcode() int32 {
	if o == nil || isNil(o.Errcode) {
		var ret int32
		return ret
	}
	return *o.Errcode
}

// GetErrcodeOk returns a tuple with the Errcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponse) GetErrcodeOk() (*int32, bool) {
	if o == nil || isNil(o.Errcode) {
		return nil, false
	}
	return o.Errcode, true
}

// HasErrcode returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponse) HasErrcode() bool {
	if o != nil && !isNil(o.Errcode) {
		return true
	}

	return false
}

// SetErrcode gets a reference to the given int32 and assigns it to the Errcode field.
func (o *GetAuthorizerInfoResponse) SetErrcode(v int32) {
	o.Errcode = &v
}

// GetErrmsg returns the Errmsg field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponse) GetErrmsg() string {
	if o == nil || isNil(o.Errmsg) {
		var ret string
		return ret
	}
	return *o.Errmsg
}

// GetErrmsgOk returns a tuple with the Errmsg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponse) GetErrmsgOk() (*string, bool) {
	if o == nil || isNil(o.Errmsg) {
		return nil, false
	}
	return o.Errmsg, true
}

// HasErrmsg returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponse) HasErrmsg() bool {
	if o != nil && !isNil(o.Errmsg) {
		return true
	}

	return false
}

// SetErrmsg gets a reference to the given string and assigns it to the Errmsg field.
func (o *GetAuthorizerInfoResponse) SetErrmsg(v string) {
	o.Errmsg = &v
}

// GetAuthorizerInfo returns the AuthorizerInfo field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponse) GetAuthorizerInfo() GetAuthorizerInfoResponseAuthorizerInfo {
	if o == nil || isNil(o.AuthorizerInfo) {
		var ret GetAuthorizerInfoResponseAuthorizerInfo
		return ret
	}
	return *o.AuthorizerInfo
}

// GetAuthorizerInfoOk returns a tuple with the AuthorizerInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponse) GetAuthorizerInfoOk() (*GetAuthorizerInfoResponseAuthorizerInfo, bool) {
	if o == nil || isNil(o.AuthorizerInfo) {
		return nil, false
	}
	return o.AuthorizerInfo, true
}

// HasAuthorizerInfo returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponse) HasAuthorizerInfo() bool {
	if o != nil && !isNil(o.AuthorizerInfo) {
		return true
	}

	return false
}

// SetAuthorizerInfo gets a reference to the given GetAuthorizerInfoResponseAuthorizerInfo and assigns it to the AuthorizerInfo field.
func (o *GetAuthorizerInfoResponse) SetAuthorizerInfo(v GetAuthorizerInfoResponseAuthorizerInfo) {
	o.AuthorizerInfo = &v
}

// GetAuthorizationInfo returns the AuthorizationInfo field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponse) GetAuthorizationInfo() GetAuthorizerInfoResponseAuthorizationInfo {
	if o == nil || isNil(o.AuthorizationInfo) {
		var ret GetAuthorizerInfoResponseAuthorizationInfo
		return ret
	}
	return *o.AuthorizationInfo
}

// GetAuthorizationInfoOk returns a tuple with the AuthorizationInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponse) GetAuthorizationInfoOk() (*GetAuthorizerInfoResponseAuthorizationInfo, bool) {
	if o == nil || isNil(o.AuthorizationInfo) {
		return nil, false
	}
	return o.AuthorizationInfo, true
}

// HasAuthorizationInfo returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponse) HasAuthorizationInfo() bool {
	if o != nil && !isNil(o.AuthorizationInfo) {
		return true
	}

	return false
}

// SetAuthorizationInfo gets a reference to the given GetAuthorizerInfoResponseAuthorizationInfo and assigns it to the AuthorizationInfo field.
func (o *GetAuthorizerInfoResponse) SetAuthorizationInfo(v GetAuthorizerInfoResponseAuthorizationInfo) {
	o.AuthorizationInfo = &v
}

func (o GetAuthorizerInfoResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAuthorizerInfoResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Errcode) {
		toSerialize["errcode"] = o.Errcode
	}
	if !isNil(o.Errmsg) {
		toSerialize["errmsg"] = o.Errmsg
	}
	if !isNil(o.AuthorizerInfo) {
		toSerialize["authorizer_info"] = o.AuthorizerInfo
	}
	if !isNil(o.AuthorizationInfo) {
		toSerialize["authorization_info"] = o.AuthorizationInfo
	}
	return toSerialize, nil
}

type NullableGetAuthorizerInfoResponse struct {
	value *GetAuthorizerInfoResponse
	isSet bool
}

func (v NullableGetAuthorizerInfoResponse) Get() *GetAuthorizerInfoResponse {
	return v.value
}

func (v *NullableGetAuthorizerInfoResponse) Set(val *GetAuthorizerInfoResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAuthorizerInfoResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAuthorizerInfoResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAuthorizerInfoResponse(val *GetAuthorizerInfoResponse) *NullableGetAuthorizerInfoResponse {
	return &NullableGetAuthorizerInfoResponse{value: val, isSet: true}
}

func (v NullableGetAuthorizerInfoResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAuthorizerInfoResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
