/*
微信第三方平台授权相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package third_part_auth

import (
	"encoding/json"
)

// checks if the GetAuthorizerInfoResponseAuthorizerInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAuthorizerInfoResponseAuthorizerInfo{}

// GetAuthorizerInfoResponseAuthorizerInfo struct for GetAuthorizerInfoResponseAuthorizerInfo
type GetAuthorizerInfoResponseAuthorizerInfo struct {
	// 昵称
	NickName *string `json:"nick_name,omitempty"`
	// 头像
	HeadImg         *string                                                 `json:"head_img,omitempty"`
	ServiceTypeInfo *GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo `json:"service_type_info,omitempty"`
	VerifyTypeInfo  *GetAuthorizerInfoResponseAuthorizerInfoVerifyTypeInfo  `json:"verify_type_info,omitempty"`
	// 原始 ID
	UserName *string `json:"user_name,omitempty"`
	// 主体名称
	PrincipalName *string `json:"principal_name,omitempty"`
	// 公众号所设置的微信号，可能为空
	Alias        *string                                              `json:"alias,omitempty"`
	BusinessInfo *GetAuthorizerInfoResponseAuthorizerInfoBusinessInfo `json:"business_info,omitempty"`
	// 二维码图片的 URL，开发者最好自行也进行保存
	QrcodeUrl *string `json:"qrcode_url,omitempty"`
	// 帐号介绍
	Signature       *string                                                 `json:"signature,omitempty"`
	MiniProgramInfo *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo `json:"MiniProgramInfo,omitempty"`
}

// NewGetAuthorizerInfoResponseAuthorizerInfo instantiates a new GetAuthorizerInfoResponseAuthorizerInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAuthorizerInfoResponseAuthorizerInfo() *GetAuthorizerInfoResponseAuthorizerInfo {
	this := GetAuthorizerInfoResponseAuthorizerInfo{}
	return &this
}

// NewGetAuthorizerInfoResponseAuthorizerInfoWithDefaults instantiates a new GetAuthorizerInfoResponseAuthorizerInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAuthorizerInfoResponseAuthorizerInfoWithDefaults() *GetAuthorizerInfoResponseAuthorizerInfo {
	this := GetAuthorizerInfoResponseAuthorizerInfo{}
	return &this
}

// GetNickName returns the NickName field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) GetNickName() string {
	if o == nil || isNil(o.NickName) {
		var ret string
		return ret
	}
	return *o.NickName
}

// GetNickNameOk returns a tuple with the NickName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) GetNickNameOk() (*string, bool) {
	if o == nil || isNil(o.NickName) {
		return nil, false
	}
	return o.NickName, true
}

// HasNickName returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) HasNickName() bool {
	if o != nil && !isNil(o.NickName) {
		return true
	}

	return false
}

// SetNickName gets a reference to the given string and assigns it to the NickName field.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) SetNickName(v string) {
	o.NickName = &v
}

// GetHeadImg returns the HeadImg field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) GetHeadImg() string {
	if o == nil || isNil(o.HeadImg) {
		var ret string
		return ret
	}
	return *o.HeadImg
}

// GetHeadImgOk returns a tuple with the HeadImg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) GetHeadImgOk() (*string, bool) {
	if o == nil || isNil(o.HeadImg) {
		return nil, false
	}
	return o.HeadImg, true
}

// HasHeadImg returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) HasHeadImg() bool {
	if o != nil && !isNil(o.HeadImg) {
		return true
	}

	return false
}

// SetHeadImg gets a reference to the given string and assigns it to the HeadImg field.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) SetHeadImg(v string) {
	o.HeadImg = &v
}

// GetServiceTypeInfo returns the ServiceTypeInfo field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) GetServiceTypeInfo() GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo {
	if o == nil || isNil(o.ServiceTypeInfo) {
		var ret GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo
		return ret
	}
	return *o.ServiceTypeInfo
}

// GetServiceTypeInfoOk returns a tuple with the ServiceTypeInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) GetServiceTypeInfoOk() (*GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo, bool) {
	if o == nil || isNil(o.ServiceTypeInfo) {
		return nil, false
	}
	return o.ServiceTypeInfo, true
}

// HasServiceTypeInfo returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) HasServiceTypeInfo() bool {
	if o != nil && !isNil(o.ServiceTypeInfo) {
		return true
	}

	return false
}

// SetServiceTypeInfo gets a reference to the given GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo and assigns it to the ServiceTypeInfo field.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) SetServiceTypeInfo(v GetAuthorizerInfoResponseAuthorizerInfoServiceTypeInfo) {
	o.ServiceTypeInfo = &v
}

// GetVerifyTypeInfo returns the VerifyTypeInfo field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) GetVerifyTypeInfo() GetAuthorizerInfoResponseAuthorizerInfoVerifyTypeInfo {
	if o == nil || isNil(o.VerifyTypeInfo) {
		var ret GetAuthorizerInfoResponseAuthorizerInfoVerifyTypeInfo
		return ret
	}
	return *o.VerifyTypeInfo
}

// GetVerifyTypeInfoOk returns a tuple with the VerifyTypeInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) GetVerifyTypeInfoOk() (*GetAuthorizerInfoResponseAuthorizerInfoVerifyTypeInfo, bool) {
	if o == nil || isNil(o.VerifyTypeInfo) {
		return nil, false
	}
	return o.VerifyTypeInfo, true
}

// HasVerifyTypeInfo returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) HasVerifyTypeInfo() bool {
	if o != nil && !isNil(o.VerifyTypeInfo) {
		return true
	}

	return false
}

// SetVerifyTypeInfo gets a reference to the given GetAuthorizerInfoResponseAuthorizerInfoVerifyTypeInfo and assigns it to the VerifyTypeInfo field.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) SetVerifyTypeInfo(v GetAuthorizerInfoResponseAuthorizerInfoVerifyTypeInfo) {
	o.VerifyTypeInfo = &v
}

// GetUserName returns the UserName field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) GetUserName() string {
	if o == nil || isNil(o.UserName) {
		var ret string
		return ret
	}
	return *o.UserName
}

// GetUserNameOk returns a tuple with the UserName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) GetUserNameOk() (*string, bool) {
	if o == nil || isNil(o.UserName) {
		return nil, false
	}
	return o.UserName, true
}

// HasUserName returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) HasUserName() bool {
	if o != nil && !isNil(o.UserName) {
		return true
	}

	return false
}

// SetUserName gets a reference to the given string and assigns it to the UserName field.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) SetUserName(v string) {
	o.UserName = &v
}

// GetPrincipalName returns the PrincipalName field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) GetPrincipalName() string {
	if o == nil || isNil(o.PrincipalName) {
		var ret string
		return ret
	}
	return *o.PrincipalName
}

// GetPrincipalNameOk returns a tuple with the PrincipalName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) GetPrincipalNameOk() (*string, bool) {
	if o == nil || isNil(o.PrincipalName) {
		return nil, false
	}
	return o.PrincipalName, true
}

// HasPrincipalName returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) HasPrincipalName() bool {
	if o != nil && !isNil(o.PrincipalName) {
		return true
	}

	return false
}

// SetPrincipalName gets a reference to the given string and assigns it to the PrincipalName field.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) SetPrincipalName(v string) {
	o.PrincipalName = &v
}

// GetAlias returns the Alias field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) GetAlias() string {
	if o == nil || isNil(o.Alias) {
		var ret string
		return ret
	}
	return *o.Alias
}

// GetAliasOk returns a tuple with the Alias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) GetAliasOk() (*string, bool) {
	if o == nil || isNil(o.Alias) {
		return nil, false
	}
	return o.Alias, true
}

// HasAlias returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) HasAlias() bool {
	if o != nil && !isNil(o.Alias) {
		return true
	}

	return false
}

// SetAlias gets a reference to the given string and assigns it to the Alias field.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) SetAlias(v string) {
	o.Alias = &v
}

// GetBusinessInfo returns the BusinessInfo field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) GetBusinessInfo() GetAuthorizerInfoResponseAuthorizerInfoBusinessInfo {
	if o == nil || isNil(o.BusinessInfo) {
		var ret GetAuthorizerInfoResponseAuthorizerInfoBusinessInfo
		return ret
	}
	return *o.BusinessInfo
}

// GetBusinessInfoOk returns a tuple with the BusinessInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) GetBusinessInfoOk() (*GetAuthorizerInfoResponseAuthorizerInfoBusinessInfo, bool) {
	if o == nil || isNil(o.BusinessInfo) {
		return nil, false
	}
	return o.BusinessInfo, true
}

// HasBusinessInfo returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) HasBusinessInfo() bool {
	if o != nil && !isNil(o.BusinessInfo) {
		return true
	}

	return false
}

// SetBusinessInfo gets a reference to the given GetAuthorizerInfoResponseAuthorizerInfoBusinessInfo and assigns it to the BusinessInfo field.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) SetBusinessInfo(v GetAuthorizerInfoResponseAuthorizerInfoBusinessInfo) {
	o.BusinessInfo = &v
}

// GetQrcodeUrl returns the QrcodeUrl field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) GetQrcodeUrl() string {
	if o == nil || isNil(o.QrcodeUrl) {
		var ret string
		return ret
	}
	return *o.QrcodeUrl
}

// GetQrcodeUrlOk returns a tuple with the QrcodeUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) GetQrcodeUrlOk() (*string, bool) {
	if o == nil || isNil(o.QrcodeUrl) {
		return nil, false
	}
	return o.QrcodeUrl, true
}

// HasQrcodeUrl returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) HasQrcodeUrl() bool {
	if o != nil && !isNil(o.QrcodeUrl) {
		return true
	}

	return false
}

// SetQrcodeUrl gets a reference to the given string and assigns it to the QrcodeUrl field.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) SetQrcodeUrl(v string) {
	o.QrcodeUrl = &v
}

// GetSignature returns the Signature field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) GetSignature() string {
	if o == nil || isNil(o.Signature) {
		var ret string
		return ret
	}
	return *o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) GetSignatureOk() (*string, bool) {
	if o == nil || isNil(o.Signature) {
		return nil, false
	}
	return o.Signature, true
}

// HasSignature returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) HasSignature() bool {
	if o != nil && !isNil(o.Signature) {
		return true
	}

	return false
}

// SetSignature gets a reference to the given string and assigns it to the Signature field.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) SetSignature(v string) {
	o.Signature = &v
}

// GetMiniProgramInfo returns the MiniProgramInfo field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) GetMiniProgramInfo() GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo {
	if o == nil || isNil(o.MiniProgramInfo) {
		var ret GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo
		return ret
	}
	return *o.MiniProgramInfo
}

// GetMiniProgramInfoOk returns a tuple with the MiniProgramInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) GetMiniProgramInfoOk() (*GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo, bool) {
	if o == nil || isNil(o.MiniProgramInfo) {
		return nil, false
	}
	return o.MiniProgramInfo, true
}

// HasMiniProgramInfo returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) HasMiniProgramInfo() bool {
	if o != nil && !isNil(o.MiniProgramInfo) {
		return true
	}

	return false
}

// SetMiniProgramInfo gets a reference to the given GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo and assigns it to the MiniProgramInfo field.
func (o *GetAuthorizerInfoResponseAuthorizerInfo) SetMiniProgramInfo(v GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo) {
	o.MiniProgramInfo = &v
}

func (o GetAuthorizerInfoResponseAuthorizerInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAuthorizerInfoResponseAuthorizerInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.NickName) {
		toSerialize["nick_name"] = o.NickName
	}
	if !isNil(o.HeadImg) {
		toSerialize["head_img"] = o.HeadImg
	}
	if !isNil(o.ServiceTypeInfo) {
		toSerialize["service_type_info"] = o.ServiceTypeInfo
	}
	if !isNil(o.VerifyTypeInfo) {
		toSerialize["verify_type_info"] = o.VerifyTypeInfo
	}
	if !isNil(o.UserName) {
		toSerialize["user_name"] = o.UserName
	}
	if !isNil(o.PrincipalName) {
		toSerialize["principal_name"] = o.PrincipalName
	}
	if !isNil(o.Alias) {
		toSerialize["alias"] = o.Alias
	}
	if !isNil(o.BusinessInfo) {
		toSerialize["business_info"] = o.BusinessInfo
	}
	if !isNil(o.QrcodeUrl) {
		toSerialize["qrcode_url"] = o.QrcodeUrl
	}
	if !isNil(o.Signature) {
		toSerialize["signature"] = o.Signature
	}
	if !isNil(o.MiniProgramInfo) {
		toSerialize["MiniProgramInfo"] = o.MiniProgramInfo
	}
	return toSerialize, nil
}

type NullableGetAuthorizerInfoResponseAuthorizerInfo struct {
	value *GetAuthorizerInfoResponseAuthorizerInfo
	isSet bool
}

func (v NullableGetAuthorizerInfoResponseAuthorizerInfo) Get() *GetAuthorizerInfoResponseAuthorizerInfo {
	return v.value
}

func (v *NullableGetAuthorizerInfoResponseAuthorizerInfo) Set(val *GetAuthorizerInfoResponseAuthorizerInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAuthorizerInfoResponseAuthorizerInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAuthorizerInfoResponseAuthorizerInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAuthorizerInfoResponseAuthorizerInfo(val *GetAuthorizerInfoResponseAuthorizerInfo) *NullableGetAuthorizerInfoResponseAuthorizerInfo {
	return &NullableGetAuthorizerInfoResponseAuthorizerInfo{value: val, isSet: true}
}

func (v NullableGetAuthorizerInfoResponseAuthorizerInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAuthorizerInfoResponseAuthorizerInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
