/*
微信第三方平台授权相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package third_part_auth

import (
	"encoding/json"
)

// checks if the GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo{}

// GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo 小程序配置，根据这个字段判断是否为小程序类型授权
type GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo struct {
	VisitStatus *int32                                                                  `json:"visit_status,omitempty"`
	Network     *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork          `json:"network,omitempty"`
	Categories  []GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner `json:"categories,omitempty"`
}

// NewGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo instantiates a new GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo() *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo {
	this := GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo{}
	return &this
}

// NewGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoWithDefaults instantiates a new GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoWithDefaults() *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo {
	this := GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo{}
	return &this
}

// GetVisitStatus returns the VisitStatus field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo) GetVisitStatus() int32 {
	if o == nil || isNil(o.VisitStatus) {
		var ret int32
		return ret
	}
	return *o.VisitStatus
}

// GetVisitStatusOk returns a tuple with the VisitStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo) GetVisitStatusOk() (*int32, bool) {
	if o == nil || isNil(o.VisitStatus) {
		return nil, false
	}
	return o.VisitStatus, true
}

// HasVisitStatus returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo) HasVisitStatus() bool {
	if o != nil && !isNil(o.VisitStatus) {
		return true
	}

	return false
}

// SetVisitStatus gets a reference to the given int32 and assigns it to the VisitStatus field.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo) SetVisitStatus(v int32) {
	o.VisitStatus = &v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo) GetNetwork() GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork {
	if o == nil || isNil(o.Network) {
		var ret GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo) GetNetworkOk() (*GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork, bool) {
	if o == nil || isNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo) HasNetwork() bool {
	if o != nil && !isNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork and assigns it to the Network field.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo) SetNetwork(v GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoNetwork) {
	o.Network = &v
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo) GetCategories() []GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner {
	if o == nil || isNil(o.Categories) {
		var ret []GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner
		return ret
	}
	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo) GetCategoriesOk() ([]GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner, bool) {
	if o == nil || isNil(o.Categories) {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo) HasCategories() bool {
	if o != nil && !isNil(o.Categories) {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner and assigns it to the Categories field.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo) SetCategories(v []GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner) {
	o.Categories = v
}

func (o GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.VisitStatus) {
		toSerialize["visit_status"] = o.VisitStatus
	}
	if !isNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	if !isNil(o.Categories) {
		toSerialize["categories"] = o.Categories
	}
	return toSerialize, nil
}

type NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo struct {
	value *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo
	isSet bool
}

func (v NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo) Get() *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo {
	return v.value
}

func (v *NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo) Set(val *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo(val *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo) *NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo {
	return &NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo{value: val, isSet: true}
}

func (v NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
