/*
微信第三方平台授权相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package third_part_auth

import (
	"encoding/json"
)

// checks if the StartPushTicketRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StartPushTicketRequest{}

// StartPushTicketRequest struct for StartPushTicketRequest
type StartPushTicketRequest struct {
	// 平台型第三方平台的appid
	ComponentAppid string `json:"component_appid"`
	// 平台型第三方平台的APPSECRET
	ComponentSecret string `json:"component_secret"`
}

// NewStartPushTicketRequest instantiates a new StartPushTicketRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStartPushTicketRequest(componentAppid string, componentSecret string) *StartPushTicketRequest {
	this := StartPushTicketRequest{}
	this.ComponentAppid = componentAppid
	this.ComponentSecret = componentSecret
	return &this
}

// NewStartPushTicketRequestWithDefaults instantiates a new StartPushTicketRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStartPushTicketRequestWithDefaults() *StartPushTicketRequest {
	this := StartPushTicketRequest{}
	return &this
}

// GetComponentAppid returns the ComponentAppid field value
func (o *StartPushTicketRequest) GetComponentAppid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ComponentAppid
}

// GetComponentAppidOk returns a tuple with the ComponentAppid field value
// and a boolean to check if the value has been set.
func (o *StartPushTicketRequest) GetComponentAppidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ComponentAppid, true
}

// SetComponentAppid sets field value
func (o *StartPushTicketRequest) SetComponentAppid(v string) {
	o.ComponentAppid = v
}

// GetComponentSecret returns the ComponentSecret field value
func (o *StartPushTicketRequest) GetComponentSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ComponentSecret
}

// GetComponentSecretOk returns a tuple with the ComponentSecret field value
// and a boolean to check if the value has been set.
func (o *StartPushTicketRequest) GetComponentSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ComponentSecret, true
}

// SetComponentSecret sets field value
func (o *StartPushTicketRequest) SetComponentSecret(v string) {
	o.ComponentSecret = v
}

func (o StartPushTicketRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StartPushTicketRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["component_appid"] = o.ComponentAppid
	toSerialize["component_secret"] = o.ComponentSecret
	return toSerialize, nil
}

type NullableStartPushTicketRequest struct {
	value *StartPushTicketRequest
	isSet bool
}

func (v NullableStartPushTicketRequest) Get() *StartPushTicketRequest {
	return v.value
}

func (v *NullableStartPushTicketRequest) Set(val *StartPushTicketRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableStartPushTicketRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableStartPushTicketRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStartPushTicketRequest(val *StartPushTicketRequest) *NullableStartPushTicketRequest {
	return &NullableStartPushTicketRequest{value: val, isSet: true}
}

func (v NullableStartPushTicketRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStartPushTicketRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
