/*
微信第三方平台授权相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package third_part_auth

import (
	"encoding/json"
)

// checks if the AuthorizerTokenResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorizerTokenResponse{}

// AuthorizerTokenResponse struct for AuthorizerTokenResponse
type AuthorizerTokenResponse struct {
	// 返回码
	Errcode *int32 `json:"errcode,omitempty"`
	// 对返回码的文本描述内容
	Errmsg *string `json:"errmsg,omitempty"`
	// 有效期，单位：秒
	ExpiresIn *int32 `json:"expires_in,omitempty"`
	// 授权方令牌
	AuthorizerAccessToken *string `json:"authorizer_access_token,omitempty"`
	// 刷新令牌
	AuthorizerRefreshToken *string `json:"authorizer_refresh_token,omitempty"`
}

// NewAuthorizerTokenResponse instantiates a new AuthorizerTokenResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorizerTokenResponse() *AuthorizerTokenResponse {
	this := AuthorizerTokenResponse{}
	return &this
}

// NewAuthorizerTokenResponseWithDefaults instantiates a new AuthorizerTokenResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorizerTokenResponseWithDefaults() *AuthorizerTokenResponse {
	this := AuthorizerTokenResponse{}
	return &this
}

// GetErrcode returns the Errcode field value if set, zero value otherwise.
func (o *AuthorizerTokenResponse) GetErrcode() int32 {
	if o == nil || isNil(o.Errcode) {
		var ret int32
		return ret
	}
	return *o.Errcode
}

// GetErrcodeOk returns a tuple with the Errcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizerTokenResponse) GetErrcodeOk() (*int32, bool) {
	if o == nil || isNil(o.Errcode) {
		return nil, false
	}
	return o.Errcode, true
}

// HasErrcode returns a boolean if a field has been set.
func (o *AuthorizerTokenResponse) HasErrcode() bool {
	if o != nil && !isNil(o.Errcode) {
		return true
	}

	return false
}

// SetErrcode gets a reference to the given int32 and assigns it to the Errcode field.
func (o *AuthorizerTokenResponse) SetErrcode(v int32) {
	o.Errcode = &v
}

// GetErrmsg returns the Errmsg field value if set, zero value otherwise.
func (o *AuthorizerTokenResponse) GetErrmsg() string {
	if o == nil || isNil(o.Errmsg) {
		var ret string
		return ret
	}
	return *o.Errmsg
}

// GetErrmsgOk returns a tuple with the Errmsg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizerTokenResponse) GetErrmsgOk() (*string, bool) {
	if o == nil || isNil(o.Errmsg) {
		return nil, false
	}
	return o.Errmsg, true
}

// HasErrmsg returns a boolean if a field has been set.
func (o *AuthorizerTokenResponse) HasErrmsg() bool {
	if o != nil && !isNil(o.Errmsg) {
		return true
	}

	return false
}

// SetErrmsg gets a reference to the given string and assigns it to the Errmsg field.
func (o *AuthorizerTokenResponse) SetErrmsg(v string) {
	o.Errmsg = &v
}

// GetExpiresIn returns the ExpiresIn field value if set, zero value otherwise.
func (o *AuthorizerTokenResponse) GetExpiresIn() int32 {
	if o == nil || isNil(o.ExpiresIn) {
		var ret int32
		return ret
	}
	return *o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizerTokenResponse) GetExpiresInOk() (*int32, bool) {
	if o == nil || isNil(o.ExpiresIn) {
		return nil, false
	}
	return o.ExpiresIn, true
}

// HasExpiresIn returns a boolean if a field has been set.
func (o *AuthorizerTokenResponse) HasExpiresIn() bool {
	if o != nil && !isNil(o.ExpiresIn) {
		return true
	}

	return false
}

// SetExpiresIn gets a reference to the given int32 and assigns it to the ExpiresIn field.
func (o *AuthorizerTokenResponse) SetExpiresIn(v int32) {
	o.ExpiresIn = &v
}

// GetAuthorizerAccessToken returns the AuthorizerAccessToken field value if set, zero value otherwise.
func (o *AuthorizerTokenResponse) GetAuthorizerAccessToken() string {
	if o == nil || isNil(o.AuthorizerAccessToken) {
		var ret string
		return ret
	}
	return *o.AuthorizerAccessToken
}

// GetAuthorizerAccessTokenOk returns a tuple with the AuthorizerAccessToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizerTokenResponse) GetAuthorizerAccessTokenOk() (*string, bool) {
	if o == nil || isNil(o.AuthorizerAccessToken) {
		return nil, false
	}
	return o.AuthorizerAccessToken, true
}

// HasAuthorizerAccessToken returns a boolean if a field has been set.
func (o *AuthorizerTokenResponse) HasAuthorizerAccessToken() bool {
	if o != nil && !isNil(o.AuthorizerAccessToken) {
		return true
	}

	return false
}

// SetAuthorizerAccessToken gets a reference to the given string and assigns it to the AuthorizerAccessToken field.
func (o *AuthorizerTokenResponse) SetAuthorizerAccessToken(v string) {
	o.AuthorizerAccessToken = &v
}

// GetAuthorizerRefreshToken returns the AuthorizerRefreshToken field value if set, zero value otherwise.
func (o *AuthorizerTokenResponse) GetAuthorizerRefreshToken() string {
	if o == nil || isNil(o.AuthorizerRefreshToken) {
		var ret string
		return ret
	}
	return *o.AuthorizerRefreshToken
}

// GetAuthorizerRefreshTokenOk returns a tuple with the AuthorizerRefreshToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizerTokenResponse) GetAuthorizerRefreshTokenOk() (*string, bool) {
	if o == nil || isNil(o.AuthorizerRefreshToken) {
		return nil, false
	}
	return o.AuthorizerRefreshToken, true
}

// HasAuthorizerRefreshToken returns a boolean if a field has been set.
func (o *AuthorizerTokenResponse) HasAuthorizerRefreshToken() bool {
	if o != nil && !isNil(o.AuthorizerRefreshToken) {
		return true
	}

	return false
}

// SetAuthorizerRefreshToken gets a reference to the given string and assigns it to the AuthorizerRefreshToken field.
func (o *AuthorizerTokenResponse) SetAuthorizerRefreshToken(v string) {
	o.AuthorizerRefreshToken = &v
}

func (o AuthorizerTokenResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorizerTokenResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Errcode) {
		toSerialize["errcode"] = o.Errcode
	}
	if !isNil(o.Errmsg) {
		toSerialize["errmsg"] = o.Errmsg
	}
	if !isNil(o.ExpiresIn) {
		toSerialize["expires_in"] = o.ExpiresIn
	}
	if !isNil(o.AuthorizerAccessToken) {
		toSerialize["authorizer_access_token"] = o.AuthorizerAccessToken
	}
	if !isNil(o.AuthorizerRefreshToken) {
		toSerialize["authorizer_refresh_token"] = o.AuthorizerRefreshToken
	}
	return toSerialize, nil
}

type NullableAuthorizerTokenResponse struct {
	value *AuthorizerTokenResponse
	isSet bool
}

func (v NullableAuthorizerTokenResponse) Get() *AuthorizerTokenResponse {
	return v.value
}

func (v *NullableAuthorizerTokenResponse) Set(val *AuthorizerTokenResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorizerTokenResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorizerTokenResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorizerTokenResponse(val *AuthorizerTokenResponse) *NullableAuthorizerTokenResponse {
	return &NullableAuthorizerTokenResponse{value: val, isSet: true}
}

func (v NullableAuthorizerTokenResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorizerTokenResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
