/*
微信第三方平台授权相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package third_part_auth

import (
	"encoding/json"
)

// checks if the GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory{}

// GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory struct for GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory
type GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory struct {
	Id *int32 `json:"id,omitempty"`
}

// NewGetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory instantiates a new GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory() *GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory {
	this := GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory{}
	return &this
}

// NewGetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategoryWithDefaults instantiates a new GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategoryWithDefaults() *GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory {
	this := GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory) GetId() int32 {
	if o == nil || isNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory) GetIdOk() (*int32, bool) {
	if o == nil || isNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory) SetId(v int32) {
	o.Id = &v
}

func (o GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableGetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory struct {
	value *GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory
	isSet bool
}

func (v NullableGetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory) Get() *GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory {
	return v.value
}

func (v *NullableGetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory) Set(val *GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory(val *GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory) *NullableGetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory {
	return &NullableGetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory{value: val, isSet: true}
}

func (v NullableGetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAuthorizerInfoResponseAuthorizationInfoFuncInfoInnerFuncscopeCategory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
