/*
微信第三方平台授权相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package third_part_auth

import (
	"encoding/json"
)

// checks if the GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner{}

// GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner struct for GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner
type GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner struct {
	// 帐号介绍
	First *string `json:"first,omitempty"`
	// 帐号介绍
	Second *string `json:"second,omitempty"`
}

// NewGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner instantiates a new GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner() *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner {
	this := GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner{}
	return &this
}

// NewGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInnerWithDefaults instantiates a new GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInnerWithDefaults() *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner {
	this := GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner{}
	return &this
}

// GetFirst returns the First field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner) GetFirst() string {
	if o == nil || isNil(o.First) {
		var ret string
		return ret
	}
	return *o.First
}

// GetFirstOk returns a tuple with the First field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner) GetFirstOk() (*string, bool) {
	if o == nil || isNil(o.First) {
		return nil, false
	}
	return o.First, true
}

// HasFirst returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner) HasFirst() bool {
	if o != nil && !isNil(o.First) {
		return true
	}

	return false
}

// SetFirst gets a reference to the given string and assigns it to the First field.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner) SetFirst(v string) {
	o.First = &v
}

// GetSecond returns the Second field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner) GetSecond() string {
	if o == nil || isNil(o.Second) {
		var ret string
		return ret
	}
	return *o.Second
}

// GetSecondOk returns a tuple with the Second field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner) GetSecondOk() (*string, bool) {
	if o == nil || isNil(o.Second) {
		return nil, false
	}
	return o.Second, true
}

// HasSecond returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner) HasSecond() bool {
	if o != nil && !isNil(o.Second) {
		return true
	}

	return false
}

// SetSecond gets a reference to the given string and assigns it to the Second field.
func (o *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner) SetSecond(v string) {
	o.Second = &v
}

func (o GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.First) {
		toSerialize["first"] = o.First
	}
	if !isNil(o.Second) {
		toSerialize["second"] = o.Second
	}
	return toSerialize, nil
}

type NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner struct {
	value *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner
	isSet bool
}

func (v NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner) Get() *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner {
	return v.value
}

func (v *NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner) Set(val *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner(val *GetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner) *NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner {
	return &NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner{value: val, isSet: true}
}

func (v NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAuthorizerInfoResponseAuthorizerInfoMiniProgramInfoCategoriesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
