/*
微信第三方平台授权相关接口

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package third_part_auth

import (
	"encoding/json"
)

// checks if the GetAuthorizerInfoResponseAuthorizationInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAuthorizerInfoResponseAuthorizationInfo{}

// GetAuthorizerInfoResponseAuthorizationInfo struct for GetAuthorizerInfoResponseAuthorizationInfo
type GetAuthorizerInfoResponseAuthorizationInfo struct {
	// 授权方 appid
	AuthorizationAppid *string `json:"authorization_appid,omitempty"`
	// 授权给开发者的权限集列表
	FuncInfo []GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInner `json:"func_info,omitempty"`
}

// NewGetAuthorizerInfoResponseAuthorizationInfo instantiates a new GetAuthorizerInfoResponseAuthorizationInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAuthorizerInfoResponseAuthorizationInfo() *GetAuthorizerInfoResponseAuthorizationInfo {
	this := GetAuthorizerInfoResponseAuthorizationInfo{}
	return &this
}

// NewGetAuthorizerInfoResponseAuthorizationInfoWithDefaults instantiates a new GetAuthorizerInfoResponseAuthorizationInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAuthorizerInfoResponseAuthorizationInfoWithDefaults() *GetAuthorizerInfoResponseAuthorizationInfo {
	this := GetAuthorizerInfoResponseAuthorizationInfo{}
	return &this
}

// GetAuthorizationAppid returns the AuthorizationAppid field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizationInfo) GetAuthorizationAppid() string {
	if o == nil || isNil(o.AuthorizationAppid) {
		var ret string
		return ret
	}
	return *o.AuthorizationAppid
}

// GetAuthorizationAppidOk returns a tuple with the AuthorizationAppid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizationInfo) GetAuthorizationAppidOk() (*string, bool) {
	if o == nil || isNil(o.AuthorizationAppid) {
		return nil, false
	}
	return o.AuthorizationAppid, true
}

// HasAuthorizationAppid returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizationInfo) HasAuthorizationAppid() bool {
	if o != nil && !isNil(o.AuthorizationAppid) {
		return true
	}

	return false
}

// SetAuthorizationAppid gets a reference to the given string and assigns it to the AuthorizationAppid field.
func (o *GetAuthorizerInfoResponseAuthorizationInfo) SetAuthorizationAppid(v string) {
	o.AuthorizationAppid = &v
}

// GetFuncInfo returns the FuncInfo field value if set, zero value otherwise.
func (o *GetAuthorizerInfoResponseAuthorizationInfo) GetFuncInfo() []GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInner {
	if o == nil || isNil(o.FuncInfo) {
		var ret []GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInner
		return ret
	}
	return o.FuncInfo
}

// GetFuncInfoOk returns a tuple with the FuncInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthorizerInfoResponseAuthorizationInfo) GetFuncInfoOk() ([]GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInner, bool) {
	if o == nil || isNil(o.FuncInfo) {
		return nil, false
	}
	return o.FuncInfo, true
}

// HasFuncInfo returns a boolean if a field has been set.
func (o *GetAuthorizerInfoResponseAuthorizationInfo) HasFuncInfo() bool {
	if o != nil && !isNil(o.FuncInfo) {
		return true
	}

	return false
}

// SetFuncInfo gets a reference to the given []GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInner and assigns it to the FuncInfo field.
func (o *GetAuthorizerInfoResponseAuthorizationInfo) SetFuncInfo(v []GetAuthorizerInfoResponseAuthorizationInfoFuncInfoInner) {
	o.FuncInfo = v
}

func (o GetAuthorizerInfoResponseAuthorizationInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAuthorizerInfoResponseAuthorizationInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.AuthorizationAppid) {
		toSerialize["authorization_appid"] = o.AuthorizationAppid
	}
	if !isNil(o.FuncInfo) {
		toSerialize["func_info"] = o.FuncInfo
	}
	return toSerialize, nil
}

type NullableGetAuthorizerInfoResponseAuthorizationInfo struct {
	value *GetAuthorizerInfoResponseAuthorizationInfo
	isSet bool
}

func (v NullableGetAuthorizerInfoResponseAuthorizationInfo) Get() *GetAuthorizerInfoResponseAuthorizationInfo {
	return v.value
}

func (v *NullableGetAuthorizerInfoResponseAuthorizationInfo) Set(val *GetAuthorizerInfoResponseAuthorizationInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAuthorizerInfoResponseAuthorizationInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAuthorizerInfoResponseAuthorizationInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAuthorizerInfoResponseAuthorizationInfo(val *GetAuthorizerInfoResponseAuthorizationInfo) *NullableGetAuthorizerInfoResponseAuthorizationInfo {
	return &NullableGetAuthorizerInfoResponseAuthorizationInfo{value: val, isSet: true}
}

func (v NullableGetAuthorizerInfoResponseAuthorizationInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAuthorizerInfoResponseAuthorizationInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
