openapi: 3.0.1
info:
  title: 微信公众号素材相关接口
  version: 1.0.0
servers:
- url: https://api.weixin.qq.com/cgi-bin
paths:

  /material/batchget_material:
    post:
      summary: 素材管理 /获取素材列表
      tags:
      - material
      parameters:
      - in: query
        name: access_token
        required: true
        description: access_token
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchgetMaterialRequest'
        required: true
      responses:
        "200":
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchgetMaterialResponse'

  /material/get_material:
    post:
      summary: 素材管理 /获取永久素材
      tags:
      - material
      parameters:
      - in: query
        name: access_token
        required: true
        description: access_token
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetMaterialRequest'
        required: true
      responses:
        "200":
          description: "根据获取的素材类型有不同的值"
          content:
            multipart/form-data:
              schema:
                type: string
                format: binary

 
components:
  schemas:
    GetMaterialRequest:
      properties:
        media_id:
          type: string
          description: 要获取的素材的media_id
    BatchgetMaterialRequest:
      properties:
        type:
          type: string
          description: 素材的类型，图片（image）、视频（video）、语音 （voice）、图文（news）
        offset:
          type: integer
          description: 从全部素材的该偏移位置开始返回，0表示从第一个素材 返回
        count:
          type: integer
          description: 返回素材的数量，取值在1到20之间
    BatchgetMaterialResponse:
      properties:
        errcode:
          type: integer
          description: 返回码
        errmsg:
          type: string
          description: 对返回码的文本描述内容
        total_count:
          type: integer
          description: 该类型的素材的总数
        item_count:
          type: integer
          description: 本次调用获取的素材的数量
        item:
          type: array
          items:
            type: object
            properties:
              media_id:
                type: string
              content:
                type: object
                properties:
                  news_item:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                          description: 图文消息的标题
                        thumb_media_id:
                          type: string
                          description: 图文消息的封面图片素材id（必须是永久mediaID）
                        show_cover_pic:
                          type: integer
                          description: 是否显示封面，0为false，即不显示，1为true，即显示
                        author:
                          type: string
                          description: 作者
                        digest:
                          type: string
                          description: 图文消息的摘要，仅有单图文消息才有摘要，多图文此处为空
                        content:
                          type: string
                          description: 图文消息的具体内容，支持HTML标签，必须少于2万字符，小于1M，且此处会去除JS
                        content_source_url:
                          type: string
                          description: 图文消息的原文地址，即点击“阅读原文”后的URL
                        url:
                          type: string
                          description: 图文页的URL，或者，当获取的列表是图片素材列表时，该字段是图片的URL
                        thumb_url:
                          type: string
                          description: 封面URL
              url:
                type: string
                description: 图文页的URL，或者，当获取的列表是图片素材列表时，该字段是图片的URL
              update_time:
                type: integer
                format: int64
                description: 这篇图文消息素材的最后更新时间
              name:
                type: string
                description: 文件名称 
