openapi: 3.0.1
info:
  title: 微信小程序相关接口
  version: 1.0.0
servers:
- url: https://api.weixin.qq.com

paths:
  /sns/jscode2session:
    get:
      summary: 登录凭证校验。
      tags:
      - MiniProgramAuth
      parameters:
      - in: query
        name: appid
        required: true
        description: 小程序 appId
        schema:
          type: string
      - in: query
        name: secret
        required: true
        description: 小程序 secret
        schema:
          type: string
      - in: query
        name: js_code
        required: true
        description: 登录时获取的 code
        schema:
          type: string
      - in: query
        name: grant_type
        required: true
        description: 授权类型，此处只需填写 authorization_code
        schema:
          type: string
      responses:
        "200":
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jscode2sessionRsp'
  /cgi-bin/token:
    get:
      summary: 获取小程序全局唯一后台接口调用凭据（access_token）。
      tags:
      - MiniProgramAuth
      parameters:
      - in: query
        name: appid
        required: true
        description: 小程序 appId
        schema:
          type: string
      - in: query
        name: secret
        required: true
        description: 小程序 secret
        schema:
          type: string
      - in: query
        name: grant_type
        required: true
        description: 授权类型，此处只需填写 client_credential
        schema:
          type: string
      responses:
        "200":
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRsp'


  /wxa/getwxacodeunlimit:
    get:
      summary: 获取小程序全局唯一后台接口调用凭据（access_token）。
      tags:
      - MiniProgramAuth
      parameters:
      - in: query
        name: access_token
        required: true
        description: access_token
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getwxacodeunlimitReq'
        required: true
      responses:
        "200":
          description: "二维码二进制 or getwxacodeunlimitRsp"
          content:
            multipart/form-data:
              schema:
                type: string
                format: binary
components:
  schemas:
    TokenRsp:
      properties:
        errcode:
          type: integer
          description: 返回码
        errmsg:
          type: string
          description: 对返回码的文本描述内容
        access_token:
          type: string
          description: access_token
        expires_in:
          type: integer
          description: expires_in
    jscode2sessionRsp:
      properties:
        errcode:
          type: integer
          description: 返回码
        errmsg:
          type: string
          description: 对返回码的文本描述内容
        openid:
          type: string
          description: 用户唯一标识
        session_key:
          type: string
          description: 会话密钥
        unionid:
          type: string
          description: 用户在开放平台的唯一标识符，若当前小程序已绑定到微信开放平台帐号下会返回，详见UnionID机制说明。

    getwxacodeunlimitReq:
      properties:
        scene: 
          type: string
          description: 是	最大32个可见字符，只支持数字，大小写英文以及部分特殊字符：!#$&'()*+,/:;=?@-._~，其它字符请自行编码为合法字符（因不支持%，中文无法使用 urlencode 处理，请使用其他编码方式）
        page: 
          type: string
          description: 主页	否	页面 page，例如 pages/index/index，根路径前不要填加 /，不能携带参数（参数请放在scene字段里），如果不填写这个字段，默认跳主页面
        check_path: 
          type: boolean
          description: true	否	检查page 是否存在，为 true 时 page 必须是已经发布的小程序存在的页面（否则报错）；为 false 时允许小程序未发布或者 page 不存在， 但page 有数量上限（60000个）请勿滥用
        env_version: 
          type: string	
          description: release"	否	要打开的小程序版本。正式版为 "release"，体验版为 "trial"，开发版为 "develop"
        width: 
          type: integer
          description: 430	否	二维码的宽度，单位 px，最小 280px，最大 1280px
        auto_color: 
          type: boolean
          description: false	否	自动配置线条颜色，如果颜色依然是黑色，则说明不建议配置主色调，默认 false
        line_color: 
          type: object
          properties:
            r:
              type: integer
            g:
              type: integer
            b:
              type: integer
          description: '{"r":0,"g":0,"b":0}	否	auto_color 为 false 时生效，使用 rgb 设置颜色 例如 {"r":"xxx","g":"xxx","b":"xxx"} 十进制表示'
        is_hyaline: 
          type: boolean
          description: false	否	是否需要透明底色，为 true 时，生成透明底色的小程序

    getwxacodeunlimitRsp:
      properties:
        errcode:
          type: integer
          description: 返回码
        errmsg:
          type: string
          description: 对返回码的文本描述内容